/*
 Navicat Premium Data Transfer

 Source Server         : 47.86.33.98
 Source Server Type    : MariaDB
 Source Server Version : 50568
 Source Host           : 47.86.33.98:3306
 Source Schema         : cbg_spider

 Target Server Type    : MariaDB
 Target Server Version : 50568
 File Encoding         : 65001

 Date: 16/09/2025 18:01:19
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for abnormal_equipment
-- ----------------------------
DROP TABLE IF EXISTS `abnormal_equipment`;
CREATE TABLE `abnormal_equipment`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `equip_sn` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '装备序列号',
  `equipment_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '装备数据',
  `mark_reason` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '标记原因',
  `mark_time` datetime(0) NULL DEFAULT NULL COMMENT '标记时间',
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '状态',
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `equip_sn`(`equip_sn`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for equipments
-- ----------------------------
DROP TABLE IF EXISTS `equipments`;
CREATE TABLE `equipments`  (
  `equip_sn` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '装备序列号（主键）',
  `eid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备唯一标识符',
  `equipid` int(11) NULL DEFAULT NULL COMMENT '装备ID',
  `server_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '服务器名称',
  `serverid` int(11) NULL DEFAULT NULL COMMENT '服务器ID',
  `equip_server_sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备服务器序列号',
  `seller_nickname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '卖家昵称',
  `seller_roleid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '卖家角色ID',
  `area_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '区域名称',
  `equip_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备名称',
  `equip_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备类型',
  `equip_type_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备类型名称',
  `equip_type_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '装备类型描述',
  `level` int(11) NULL DEFAULT NULL COMMENT '装备等级',
  `equip_level` int(11) NULL DEFAULT NULL COMMENT '装备等级',
  `equip_level_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备等级描述',
  `level_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '等级描述',
  `subtitle` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '副标题',
  `equip_pos` int(11) NULL DEFAULT NULL COMMENT '装备位置',
  `position` int(11) NULL DEFAULT NULL COMMENT '位置',
  `school` int(11) NULL DEFAULT NULL COMMENT '门派限制',
  `role_grade_limit` int(11) NULL DEFAULT NULL COMMENT '角色等级限制',
  `min_buyer_level` int(11) NULL DEFAULT NULL COMMENT '最低购买者等级',
  `equip_count` int(11) NULL DEFAULT NULL COMMENT '装备数量',
  `price` float NULL DEFAULT NULL COMMENT '价格',
  `price_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '价格描述',
  `unit_price_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '单价描述',
  `min_unit_price` float NULL DEFAULT NULL COMMENT '最低单价',
  `price_explanation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '价格说明',
  `accept_bargain` tinyint(1) NULL DEFAULT NULL COMMENT '接受还价',
  `bargain_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '还价信息',
  `equip_status` int(11) NULL DEFAULT NULL COMMENT '装备状态',
  `equip_status_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备状态描述',
  `status_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '状态描述',
  `onsale_expire_time_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '在售过期时间描述',
  `time_left` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '剩余时间',
  `expire_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '过期时间',
  `create_time_equip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备创建时间',
  `selling_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '销售时间',
  `selling_time_ago_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '销售时间前描述',
  `first_onsale_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '首次上架时间',
  `pass_fair_show` tinyint(1) NULL DEFAULT NULL COMMENT '是否通过公示',
  `fair_show_time` int(11) NULL DEFAULT NULL COMMENT '公示时间',
  `fair_show_end_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '公示结束时间',
  `fair_show_end_time_left` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '公示结束剩余时间',
  `fair_show_poundage` int(11) NULL DEFAULT NULL COMMENT '公示手续费',
  `hp` int(11) NULL DEFAULT NULL COMMENT '气血',
  `qixue` int(11) NULL DEFAULT NULL COMMENT '气血（别名）',
  `init_hp` int(11) NULL DEFAULT NULL COMMENT '初始气血',
  `mofa` int(11) NULL DEFAULT NULL COMMENT '魔法',
  `init_wakan` int(11) NULL DEFAULT NULL COMMENT '初始魔力',
  `mingzhong` int(11) NULL DEFAULT NULL COMMENT '命中',
  `fangyu` int(11) NULL DEFAULT NULL COMMENT '防御',
  `init_defense` int(11) NULL DEFAULT NULL COMMENT '初始防御',
  `defense` int(11) NULL DEFAULT NULL COMMENT '防御（别名）',
  `speed` int(11) NULL DEFAULT NULL COMMENT '速度',
  `minjie` int(11) NULL DEFAULT NULL COMMENT '敏捷',
  `init_dex` int(11) NULL DEFAULT NULL COMMENT '初始敏捷',
  `shanghai` int(11) NULL DEFAULT NULL COMMENT '伤害',
  `damage` int(11) NULL DEFAULT NULL COMMENT '伤害（别名）',
  `init_damage` int(11) NULL DEFAULT NULL COMMENT '初始伤害',
  `init_damage_raw` int(11) NULL DEFAULT NULL COMMENT '原始初始伤害',
  `all_damage` int(11) NULL DEFAULT NULL COMMENT '总伤害',
  `magic_damage` int(11) NULL DEFAULT NULL COMMENT '法术伤害',
  `magic_defense` int(11) NULL DEFAULT NULL COMMENT '法术防御',
  `lingli` int(11) NULL DEFAULT NULL COMMENT '灵力',
  `fengyin` int(11) NULL DEFAULT NULL COMMENT '封印',
  `anti_fengyin` int(11) NULL DEFAULT NULL COMMENT '抗封印',
  `zongshang` int(11) NULL DEFAULT NULL COMMENT '总伤',
  `expt_gongji` int(11) NULL DEFAULT NULL COMMENT '攻击修炼',
  `expt_fangyu` int(11) NULL DEFAULT NULL COMMENT '防御修炼',
  `expt_fashu` int(11) NULL DEFAULT NULL COMMENT '法术修炼',
  `expt_kangfa` int(11) NULL DEFAULT NULL COMMENT '抗法修炼',
  `max_expt_gongji` int(11) NULL DEFAULT NULL COMMENT '最大攻击修炼',
  `max_expt_fangyu` int(11) NULL DEFAULT NULL COMMENT '最大防御修炼',
  `max_expt_fashu` int(11) NULL DEFAULT NULL COMMENT '最大法术修炼',
  `max_expt_kangfa` int(11) NULL DEFAULT NULL COMMENT '最大抗法修炼',
  `sum_exp` int(11) NULL DEFAULT NULL COMMENT '总经验',
  `bb_expt_gongji` int(11) NULL DEFAULT NULL COMMENT '宝宝攻击修炼',
  `bb_expt_fangyu` int(11) NULL DEFAULT NULL COMMENT '宝宝防御修炼',
  `bb_expt_fashu` int(11) NULL DEFAULT NULL COMMENT '宝宝法术修炼',
  `bb_expt_kangfa` int(11) NULL DEFAULT NULL COMMENT '宝宝抗法修炼',
  `addon_tizhi` int(11) NULL DEFAULT NULL COMMENT '附加体质',
  `addon_liliang` int(11) NULL DEFAULT NULL COMMENT '附加力量',
  `addon_naili` int(11) NULL DEFAULT NULL COMMENT '附加耐力',
  `addon_minjie` int(11) NULL DEFAULT NULL COMMENT '附加敏捷',
  `addon_fali` int(11) NULL DEFAULT NULL COMMENT '附加法力',
  `addon_lingli` int(11) NULL DEFAULT NULL COMMENT '附加灵力',
  `addon_moli` int(11) NULL DEFAULT NULL COMMENT '附加魔力',
  `addon_total` int(11) NULL DEFAULT NULL COMMENT '附加总和',
  `addon_status` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '附加状态（套装信息）',
  `addon_skill_chance` int(11) NULL DEFAULT NULL COMMENT '附加技能几率',
  `addon_effect_chance` int(11) NULL DEFAULT NULL COMMENT '附加效果几率',
  `gem_level` int(11) NULL DEFAULT NULL COMMENT '宝石等级',
  `gem_value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '宝石数值',
  `xiang_qian_level` int(11) NULL DEFAULT NULL COMMENT '镶嵌等级',
  `jinglian_level` int(11) NULL DEFAULT NULL COMMENT '精炼等级',
  `special_skill` int(11) NULL DEFAULT NULL COMMENT '特技',
  `special_effect` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '特效',
  `suit_skill` int(11) NULL DEFAULT NULL COMMENT '套装技能',
  `suit_effect` int(11) NULL DEFAULT NULL COMMENT '套装效果',
  `collect_num` int(11) NULL DEFAULT NULL COMMENT '收藏数',
  `has_collect` tinyint(1) NULL DEFAULT NULL COMMENT '是否已收藏',
  `score` int(11) NULL DEFAULT NULL COMMENT '评分',
  `icon_index` int(11) NULL DEFAULT NULL COMMENT '图标索引',
  `icon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '图标',
  `equip_face_img` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '装备头像图片',
  `kindid` int(11) NULL DEFAULT NULL COMMENT '种类ID',
  `game_channel` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '游戏渠道',
  `game_ordersn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '游戏订单号',
  `whole_game_ordersn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '完整游戏订单号',
  `allow_cross_buy` tinyint(1) NULL DEFAULT NULL COMMENT '允许跨服购买',
  `cross_server_poundage` int(11) NULL DEFAULT NULL COMMENT '跨服手续费',
  `cross_server_poundage_origin` int(11) NULL DEFAULT NULL COMMENT '原始跨服手续费',
  `cross_server_poundage_discount` int(11) NULL DEFAULT NULL COMMENT '跨服手续费折扣',
  `cross_server_poundage_discount_label` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '跨服手续费折扣标签',
  `cross_server_poundage_display_mode` int(11) NULL DEFAULT NULL COMMENT '跨服手续费显示模式',
  `cross_server_activity_conf_discount` float NULL DEFAULT NULL COMMENT '跨服活动配置折扣',
  `activity_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '活动类型',
  `joined_seller_activity` tinyint(1) NULL DEFAULT NULL COMMENT '参与卖家活动',
  `is_split_sale` tinyint(1) NULL DEFAULT NULL COMMENT '是否拆分销售',
  `is_split_main_role` tinyint(1) NULL DEFAULT NULL COMMENT '是否拆分主角色',
  `is_split_independent_role` tinyint(1) NULL DEFAULT NULL COMMENT '是否拆分独立角色',
  `is_split_independent_equip` tinyint(1) NULL DEFAULT NULL COMMENT '是否拆分独立装备',
  `split_equip_sold_happen` tinyint(1) NULL DEFAULT NULL COMMENT '拆分装备售出发生',
  `show_split_equip_sold_remind` tinyint(1) NULL DEFAULT NULL COMMENT '显示拆分装备售出提醒',
  `is_onsale_protection_period` tinyint(1) NULL DEFAULT NULL COMMENT '是否在售保护期',
  `onsale_protection_end_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '在售保护结束时间',
  `is_vip_protection` tinyint(1) NULL DEFAULT NULL COMMENT '是否VIP保护',
  `is_time_lock` tinyint(1) NULL DEFAULT NULL COMMENT '是否时间锁定',
  `equip_in_test_server` tinyint(1) NULL DEFAULT NULL COMMENT '装备在测试服',
  `buyer_in_test_server` tinyint(1) NULL DEFAULT NULL COMMENT '购买者在测试服',
  `equip_in_allow_take_away_server` tinyint(1) NULL DEFAULT NULL COMMENT '装备在允许带走服务器',
  `is_weijianding` tinyint(1) NULL DEFAULT NULL COMMENT '是否未鉴定',
  `is_show_alipay_privilege` tinyint(1) NULL DEFAULT NULL COMMENT '是否显示支付宝特权',
  `is_seller_redpacket_flag` tinyint(1) NULL DEFAULT NULL COMMENT '卖家红包标志',
  `is_show_expert_desc` int(11) NULL DEFAULT NULL COMMENT '是否显示专家描述',
  `is_show_special_highlight` tinyint(1) NULL DEFAULT NULL COMMENT '是否显示特殊高亮',
  `is_xyq_game_role_kunpeng_reach_limit` tinyint(1) NULL DEFAULT NULL COMMENT '是否鲲鹏达到限制',
  `equip_onsale_version` int(11) NULL DEFAULT NULL COMMENT '装备在售版本',
  `storage_type` int(11) NULL DEFAULT NULL COMMENT '存储类型',
  `agent_trans_time` int(11) NULL DEFAULT NULL COMMENT '代理传输时间',
  `kol_article_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'KOL文章ID',
  `kol_share_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'KOL分享ID',
  `kol_share_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'KOL分享时间',
  `kol_share_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'KOL分享状态',
  `reco_request_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '推荐请求ID',
  `appointed_roleid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '指定角色ID',
  `play_team_cnt` int(11) NULL DEFAULT NULL COMMENT '游戏团队数量',
  `random_draw_finish_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '随机抽奖完成时间',
  `desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述',
  `large_equip_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '大装备描述',
  `desc_sumup` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述总结',
  `desc_sumup_short` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述总结简短',
  `diy_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '自定义描述',
  `rec_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '推荐描述',
  `diy_desc_pay_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '自定义描述支付信息',
  `other_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '其他信息',
  `video_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '视频信息',
  `agg_added_attrs` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '聚合附加属性',
  `dynamic_tags` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '动态标签',
  `highlight` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '高亮信息',
  `tag_key` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '标签键',
  `tag` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '标签',
  `search_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '搜索类型',
  `raw_data_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '原始数据',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`equip_sn`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for large_equip_desc_data
-- ----------------------------
DROP TABLE IF EXISTS `large_equip_desc_data`;
CREATE TABLE `large_equip_desc_data`  (
  `eid` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '关联到roles表的eid',
  `time_lock_days` int(11) NULL DEFAULT NULL COMMENT '时间锁定天数',
  `role_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `role_level` int(11) NULL DEFAULT NULL,
  `role_school` int(11) NULL DEFAULT NULL,
  `role_icon` int(11) NULL DEFAULT NULL,
  `user_num` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `hp_max` int(11) NULL DEFAULT NULL,
  `mp_max` int(11) NULL DEFAULT NULL,
  `att_all` int(11) NULL DEFAULT NULL,
  `def_all` int(11) NULL DEFAULT NULL,
  `spe_all` int(11) NULL DEFAULT NULL,
  `mag_all` int(11) NULL DEFAULT NULL,
  `damage_all` int(11) NULL DEFAULT NULL,
  `mag_dam_all` int(11) NULL DEFAULT NULL,
  `mag_def_all` int(11) NULL DEFAULT NULL,
  `dod_all` int(11) NULL DEFAULT NULL,
  `cor_all` int(11) NULL DEFAULT NULL,
  `str_all` int(11) NULL DEFAULT NULL,
  `res_all` int(11) NULL DEFAULT NULL,
  `dex_all` int(11) NULL DEFAULT NULL,
  `up_exp` int(11) NULL DEFAULT NULL,
  `sum_exp` int(11) NULL DEFAULT NULL,
  `expt_ski1` int(11) NULL DEFAULT NULL,
  `expt_ski2` int(11) NULL DEFAULT NULL,
  `expt_ski3` int(11) NULL DEFAULT NULL,
  `expt_ski4` int(11) NULL DEFAULT NULL,
  `expt_ski5` int(11) NULL DEFAULT NULL,
  `max_expt1` int(11) NULL DEFAULT NULL,
  `max_expt2` int(11) NULL DEFAULT NULL,
  `max_expt3` int(11) NULL DEFAULT NULL,
  `max_expt4` int(11) NULL DEFAULT NULL,
  `beast_ski1` int(11) NULL DEFAULT NULL,
  `beast_ski2` int(11) NULL DEFAULT NULL,
  `beast_ski3` int(11) NULL DEFAULT NULL,
  `beast_ski4` int(11) NULL DEFAULT NULL,
  `skill_point` int(11) NULL DEFAULT NULL,
  `attribute_point` int(11) NULL DEFAULT NULL,
  `potential` int(11) NULL DEFAULT NULL,
  `max_potential` int(11) NULL DEFAULT NULL,
  `cash` int(11) NULL DEFAULT NULL,
  `saving` int(11) NULL DEFAULT NULL,
  `learn_cash` int(11) NULL DEFAULT NULL,
  `zhuan_zhi` int(11) NULL DEFAULT NULL,
  `all_new_point` int(11) NULL DEFAULT NULL,
  `three_fly_lv` int(11) NULL DEFAULT NULL,
  `nine_fight_level` int(11) NULL DEFAULT NULL,
  `goodness` int(11) NULL DEFAULT NULL,
  `badness` int(11) NULL DEFAULT NULL,
  `goodness_sav` int(11) NULL DEFAULT NULL,
  `role_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `org_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `org_offer` int(11) NULL DEFAULT NULL,
  `org_position` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `marry_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `marry2_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `marry_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `community_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `community_gid` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `achievement_total` int(11) NULL DEFAULT NULL,
  `hero_score` int(11) NULL DEFAULT NULL,
  `datang_feat` int(11) NULL DEFAULT NULL,
  `sword_score` int(11) NULL DEFAULT NULL,
  `dup_score` int(11) NULL DEFAULT NULL,
  `shenqi_score` int(11) NULL DEFAULT NULL,
  `qicai_score` int(11) NULL DEFAULT NULL,
  `xianyu_score` int(11) NULL DEFAULT NULL,
  `nuts_num` int(11) NULL DEFAULT NULL,
  `cg_total_amount` int(11) NULL DEFAULT NULL,
  `cg_body_amount` int(11) NULL DEFAULT NULL,
  `cg_box_amount` int(11) NULL DEFAULT NULL,
  `xianyu_amount` int(11) NULL DEFAULT NULL,
  `energy_amount` int(11) NULL DEFAULT NULL,
  `jiyuan_amount` int(11) NULL DEFAULT NULL,
  `add_point` int(11) NULL DEFAULT NULL,
  `packet_page` int(11) NULL DEFAULT NULL,
  `rent_level` int(11) NULL DEFAULT NULL,
  `outdoor_level` int(11) NULL DEFAULT NULL,
  `farm_level` int(11) NULL DEFAULT NULL,
  `house_real_owner` int(11) NULL DEFAULT NULL,
  `pride` int(11) NULL DEFAULT NULL,
  `bid_status` int(11) NULL DEFAULT NULL,
  `ori_race` int(11) NULL DEFAULT NULL,
  `current_race` int(11) NULL DEFAULT NULL,
  `sum_amount` int(11) NULL DEFAULT NULL,
  `version_code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `pet` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `all_skills_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `all_equip_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `all_summon_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `child_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `child2_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `all_rider_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `ex_avt_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `huge_horse_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '祥瑞',
  `fabao_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '法宝',
  `lingbao_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '灵宝',
  `shenqi_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '神器',
  `idbid_desc_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '靓号描述',
  `changesch_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '转门派历史',
  `prop_kept_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '保持属性',
  `more_attr_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '更多属性',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`eid`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for pets
-- ----------------------------
DROP TABLE IF EXISTS `pets`;
CREATE TABLE `pets`  (
  `equip_sn` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '召唤兽序列号',
  `eid` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '召唤兽唯一标识符',
  `equipid` int(11) NULL DEFAULT NULL COMMENT '召唤兽ID',
  `server_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '服务器名称',
  `serverid` int(11) NULL DEFAULT NULL COMMENT '服务器ID',
  `equip_server_sn` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '召唤兽服务器序列号',
  `seller_nickname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '卖家昵称',
  `seller_roleid` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '卖家角色ID',
  `area_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '区域名称',
  `equip_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '召唤兽名称',
  `equip_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '召唤兽类型',
  `equip_type_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '召唤兽类型名称',
  `equip_type_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '召唤兽类型描述',
  `level` int(11) NULL DEFAULT NULL COMMENT '召唤兽等级',
  `equip_level` int(11) NULL DEFAULT NULL COMMENT '召唤兽等级',
  `equip_level_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '召唤兽等级描述',
  `level_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '等级描述',
  `subtitle` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '副标题',
  `equip_pos` int(11) NULL DEFAULT NULL COMMENT '召唤兽位置',
  `position` int(11) NULL DEFAULT NULL COMMENT '位置',
  `school` int(11) NULL DEFAULT NULL COMMENT '门派限制',
  `role_grade_limit` int(11) NULL DEFAULT NULL COMMENT '角色等级限制',
  `min_buyer_level` int(11) NULL DEFAULT NULL COMMENT '最低购买者等级',
  `equip_count` int(11) NULL DEFAULT NULL COMMENT '召唤兽数量',
  `price` float NULL DEFAULT NULL COMMENT '价格',
  `price_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '价格描述',
  `unit_price_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '单价描述',
  `min_unit_price` float NULL DEFAULT NULL COMMENT '最低单价',
  `price_explanation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '价格说明',
  `accept_bargain` tinyint(1) NULL DEFAULT NULL COMMENT '接受还价',
  `bargain_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '还价信息',
  `equip_status` int(11) NULL DEFAULT NULL COMMENT '召唤兽状态',
  `equip_status_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '召唤兽状态描述',
  `status_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '状态描述',
  `onsale_expire_time_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '在售过期时间描述',
  `time_left` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '剩余时间',
  `expire_time` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '过期时间',
  `create_time_equip` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '召唤兽创建时间',
  `selling_time` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '销售时间',
  `selling_time_ago_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '销售时间前描述',
  `first_onsale_time` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '首次上架时间',
  `pass_fair_show` tinyint(1) NULL DEFAULT NULL COMMENT '是否通过公示',
  `fair_show_time` int(11) NULL DEFAULT NULL COMMENT '公示时间',
  `fair_show_end_time` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '公示结束时间',
  `fair_show_end_time_left` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '公示结束剩余时间',
  `fair_show_poundage` int(11) NULL DEFAULT NULL COMMENT '公示手续费',
  `collect_num` int(11) NULL DEFAULT NULL COMMENT '收藏数',
  `has_collect` tinyint(1) NULL DEFAULT NULL COMMENT '是否收藏',
  `score` int(11) NULL DEFAULT NULL COMMENT '评分',
  `icon_index` int(11) NULL DEFAULT NULL COMMENT '图标索引',
  `icon` int(11) NULL DEFAULT NULL COMMENT '图标',
  `equip_face_img` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '召唤兽头像图片',
  `kindid` int(11) NULL DEFAULT NULL COMMENT '种类ID',
  `game_channel` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '游戏渠道',
  `game_ordersn` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '游戏订单号',
  `whole_game_ordersn` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '完整游戏订单号',
  `allow_cross_buy` tinyint(1) NULL DEFAULT NULL COMMENT '允许跨服购买',
  `cross_server_poundage` int(11) NULL DEFAULT NULL COMMENT '跨服手续费',
  `cross_server_poundage_origin` int(11) NULL DEFAULT NULL COMMENT '原始跨服手续费',
  `cross_server_poundage_discount` float NULL DEFAULT NULL COMMENT '跨服手续费折扣',
  `cross_server_poundage_discount_label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '跨服手续费折扣标签',
  `cross_server_poundage_display_mode` int(11) NULL DEFAULT NULL COMMENT '跨服手续费显示模式',
  `cross_server_activity_conf_discount` float NULL DEFAULT NULL COMMENT '跨服活动配置折扣',
  `activity_type` int(11) NULL DEFAULT NULL COMMENT '活动类型',
  `joined_seller_activity` tinyint(1) NULL DEFAULT NULL COMMENT '参与卖家活动',
  `is_split_sale` tinyint(1) NULL DEFAULT NULL COMMENT '是否拆分销售',
  `is_split_main_role` tinyint(1) NULL DEFAULT NULL COMMENT '是否拆分主角',
  `is_split_independent_role` tinyint(1) NULL DEFAULT NULL COMMENT '是否独立角色拆分',
  `is_split_independent_equip` tinyint(1) NULL DEFAULT NULL COMMENT '是否独立召唤兽拆分',
  `split_equip_sold_happen` tinyint(1) NULL DEFAULT NULL COMMENT '拆分召唤兽销售发生',
  `show_split_equip_sold_remind` tinyint(1) NULL DEFAULT NULL COMMENT '显示拆分召唤兽销售提醒',
  `is_onsale_protection_period` tinyint(1) NULL DEFAULT NULL COMMENT '是否在售保护期',
  `onsale_protection_end_time` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '在售保护结束时间',
  `is_vip_protection` tinyint(1) NULL DEFAULT NULL COMMENT '是否VIP保护',
  `is_time_lock` tinyint(1) NULL DEFAULT NULL COMMENT '是否时间锁定',
  `equip_in_test_server` tinyint(1) NULL DEFAULT NULL COMMENT '召唤兽在测试服',
  `buyer_in_test_server` tinyint(1) NULL DEFAULT NULL COMMENT '买家在测试服',
  `equip_in_allow_take_away_server` tinyint(1) NULL DEFAULT NULL COMMENT '召唤兽在允许带走服务器',
  `is_weijianding` tinyint(1) NULL DEFAULT NULL COMMENT '是否未鉴定',
  `is_show_alipay_privilege` tinyint(1) NULL DEFAULT NULL COMMENT '是否显示支付宝特权',
  `is_seller_redpacket_flag` tinyint(1) NULL DEFAULT NULL COMMENT '是否卖家红包标志',
  `is_show_expert_desc` tinyint(1) NULL DEFAULT NULL COMMENT '是否显示专家描述',
  `is_show_special_highlight` tinyint(1) NULL DEFAULT NULL COMMENT '是否显示特殊高亮',
  `is_xyq_game_role_kunpeng_reach_limit` tinyint(1) NULL DEFAULT NULL COMMENT '是否达到鲲鹏限制',
  `equip_onsale_version` int(11) NULL DEFAULT NULL COMMENT '召唤兽上架版本',
  `storage_type` int(11) NULL DEFAULT NULL COMMENT '存储类型',
  `agent_trans_time` int(11) NULL DEFAULT NULL COMMENT '代理传输时间',
  `kol_article_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'KOL文章ID',
  `kol_share_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'KOL分享ID',
  `kol_share_time` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'KOL分享时间',
  `kol_share_status` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'KOL分享状态',
  `reco_request_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '推荐请求ID',
  `appointed_roleid` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '指定角色ID',
  `play_team_cnt` int(11) NULL DEFAULT NULL COMMENT '游戏团队数量',
  `random_draw_finish_time` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '随机抽奖完成时间',
  `desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述',
  `large_equip_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '大召唤兽描述',
  `desc_sumup` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述总结',
  `desc_sumup_short` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述总结简短',
  `diy_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '自定义描述',
  `rec_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '推荐描述',
  `diy_desc_pay_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '自定义描述支付信息',
  `other_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '其他信息',
  `video_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '视频信息',
  `agg_added_attrs` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '聚合附加属性',
  `dynamic_tags` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '动态标签',
  `highlight` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '高亮信息',
  `tag_key` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '标签键',
  `tag` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '标签',
  `search_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '搜索类型',
  `pet_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的召唤兽名称',
  `type_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的类型ID',
  `pet_grade` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的召唤兽等级',
  `blood` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的气血',
  `magic` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的魔法',
  `attack` int(11) NULL DEFAULT NULL COMMENT '解析出的攻击',
  `defence` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的防御',
  `speed` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的速度',
  `soma` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的体质',
  `magic_powner` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的魔力',
  `strength` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的力量',
  `endurance` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的耐力',
  `smartness` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的敏捷',
  `potential` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的潜力',
  `wakan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的灵力',
  `max_blood` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的最大气血',
  `max_magic` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的最大魔法',
  `lifetime` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的寿命',
  `five_aptitude` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的五行',
  `attack_aptitude` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的攻击资质',
  `defence_aptitude` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的防御资质',
  `physical_aptitude` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的体力资质',
  `magic_aptitude` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的法力资质',
  `speed_aptitude` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的速度资质',
  `avoid_aptitude` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的躲避资质',
  `growth` float NULL DEFAULT NULL COMMENT '解析出的成长率',
  `all_skill` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的所有技能',
  `sp_skill` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的特殊技能',
  `is_baobao` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的是否宝宝',
  `used_qianjinlu` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的千金露使用情况',
  `sp_skill_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的特殊技能ID',
  `all_skills` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的技能列表',
  `ti_zhi_add` int(11) NULL DEFAULT NULL COMMENT '解析出的体质加点',
  `fa_li_add` int(11) NULL DEFAULT NULL COMMENT '解析出的法力加点',
  `li_liang_add` int(11) NULL DEFAULT NULL COMMENT '解析出的力量加点',
  `nai_li_add` int(11) NULL DEFAULT NULL COMMENT '解析出的耐力加点',
  `min_jie_add` int(11) NULL DEFAULT NULL COMMENT '解析出的敏捷加点',
  `jinjie` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的进阶信息',
  `lx` int(11) NULL DEFAULT NULL COMMENT '解析出的灵性',
  `jinjie_cnt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的进阶次数',
  `texing` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的特性',
  `core_close` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的核心关闭状态',
  `attack_ext` int(11) NULL DEFAULT NULL COMMENT '解析出的攻击扩展',
  `defence_ext` int(11) NULL DEFAULT NULL COMMENT '解析出的防御扩展',
  `speed_ext` int(11) NULL DEFAULT NULL COMMENT '解析出的速度扩展',
  `avoid_ext` int(11) NULL DEFAULT NULL COMMENT '解析出的躲避扩展',
  `physical_ext` int(11) NULL DEFAULT NULL COMMENT '解析出的体力扩展',
  `magic_ext` int(11) NULL DEFAULT NULL COMMENT '解析出的法力扩展',
  `neidan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的内丹',
  `equip_list` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的装备列表',
  `evol_skill_list` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的进化技能列表',
  `evol_skills` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的进化技能',
  `color` int(11) NULL DEFAULT NULL COMMENT '解析出的颜色',
  `summon_color` int(11) NULL DEFAULT NULL COMMENT '解析出的召唤兽颜色',
  `iMagDam` int(11) NULL DEFAULT NULL COMMENT '解析出的法术伤害',
  `iMagDef` int(11) NULL DEFAULT NULL COMMENT '解析出的法术防御',
  `used_sjg` int(11) NULL DEFAULT NULL COMMENT '解析出的神机阁使用情况',
  `used_yuanxiao` int(11) NULL DEFAULT NULL COMMENT '解析出的元宵使用情况',
  `used_lianshou` int(11) NULL DEFAULT NULL COMMENT '解析出的炼兽使用情况',
  `other` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '解析出的其他信息',
  `equip_list_amount` int(11) NULL DEFAULT NULL COMMENT '装备总价值（分）',
  `equip_list_amount_warning` int(11) NULL DEFAULT NULL COMMENT '装备总价值是否有异常（0：无异常，1：异常）',
  `raw_data_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '原始数据',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`equip_sn`) USING BTREE,
  UNIQUE INDEX `eid`(`eid`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `eid` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '角色唯一标识符',
  `equipid` int(11) NULL DEFAULT NULL COMMENT '角色ID',
  `equip_sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '角色序列号',
  `server_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '服务器名称',
  `serverid` int(11) NULL DEFAULT NULL COMMENT '服务器ID',
  `equip_server_sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '角色服务器序列号',
  `seller_nickname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '卖家昵称',
  `seller_roleid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '卖家角色ID',
  `area_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '区域名称',
  `equip_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '角色名称',
  `equip_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '角色类型',
  `equip_type_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '角色类型名称',
  `equip_type_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '角色类型描述',
  `level` int(11) NULL DEFAULT NULL COMMENT '角色等级',
  `equip_level` int(11) NULL DEFAULT NULL COMMENT '角色等级',
  `equip_level_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '角色等级描述',
  `level_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '等级描述',
  `subtitle` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '副标题',
  `equip_pos` int(11) NULL DEFAULT NULL COMMENT '角色位置',
  `position` int(11) NULL DEFAULT NULL COMMENT '位置',
  `school` int(11) NULL DEFAULT NULL COMMENT '门派限制',
  `role_grade_limit` int(11) NULL DEFAULT NULL COMMENT '角色等级限制',
  `min_buyer_level` int(11) NULL DEFAULT NULL COMMENT '最低购买者等级',
  `equip_count` int(11) NULL DEFAULT NULL COMMENT '角色数量',
  `history_price` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '历史价格',
  `split_price_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '装备和召唤兽估价价格描述',
  `base_price` float NULL DEFAULT 0 COMMENT '基本空号价格',
  `equip_price` float NULL DEFAULT 0 COMMENT '装备估价价格',
  `pet_price` float NULL DEFAULT 0 COMMENT '召唤兽估价价格',
  `price` float NULL DEFAULT NULL COMMENT '价格',
  `price_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '价格描述',
  `unit_price_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '单价描述',
  `min_unit_price` float NULL DEFAULT NULL COMMENT '最低单价',
  `price_explanation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '价格说明',
  `accept_bargain` int(11) NULL DEFAULT 0,
  `bargain_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '还价信息',
  `equip_status` int(11) NULL DEFAULT NULL COMMENT '角色状态',
  `equip_status_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '角色状态描述',
  `status_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '状态描述',
  `onsale_expire_time_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '在售过期时间描述',
  `time_left` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '剩余时间',
  `expire_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '过期时间',
  `selling_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '销售时间',
  `selling_time_ago_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '销售时间前描述',
  `first_onsale_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '首次上架时间',
  `pass_fair_show` int(11) NULL DEFAULT 0,
  `fair_show_time` int(11) NULL DEFAULT NULL COMMENT '公示时间',
  `fair_show_end_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '公示结束时间',
  `fair_show_end_time_left` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '公示结束剩余时间',
  `fair_show_poundage` int(11) NULL DEFAULT NULL COMMENT '公示手续费',
  `collect_num` int(11) NULL DEFAULT NULL COMMENT '收藏数',
  `has_collect` int(11) NULL DEFAULT 0,
  `score` int(11) NULL DEFAULT NULL COMMENT '评分',
  `icon_index` int(11) NULL DEFAULT NULL COMMENT '图标索引',
  `icon` int(11) NULL DEFAULT NULL COMMENT '图标',
  `equip_face_img` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '角色头像图片',
  `kindid` int(11) NULL DEFAULT NULL COMMENT '种类ID',
  `game_channel` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '游戏渠道',
  `game_ordersn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '游戏订单号',
  `whole_game_ordersn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '完整游戏订单号',
  `allow_cross_buy` int(11) NULL DEFAULT 0,
  `cross_server_poundage` int(11) NULL DEFAULT NULL COMMENT '跨服手续费',
  `cross_server_poundage_origin` int(11) NULL DEFAULT NULL COMMENT '原始跨服手续费',
  `cross_server_poundage_discount` float NULL DEFAULT NULL COMMENT '跨服手续费折扣',
  `cross_server_poundage_discount_label` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '跨服手续费折扣标签',
  `cross_server_poundage_display_mode` int(11) NULL DEFAULT NULL COMMENT '跨服手续费显示模式',
  `cross_server_activity_conf_discount` float NULL DEFAULT NULL COMMENT '跨服活动配置折扣',
  `activity_type` int(11) NULL DEFAULT NULL COMMENT '活动类型',
  `joined_seller_activity` int(11) NULL DEFAULT 0,
  `is_split_sale` int(11) NULL DEFAULT 0,
  `is_split_main_role` int(11) NULL DEFAULT 0,
  `is_split_independent_role` int(11) NULL DEFAULT 0,
  `is_split_independent_equip` int(11) NULL DEFAULT 0,
  `split_equip_sold_happen` int(11) NULL DEFAULT 0,
  `show_split_equip_sold_remind` int(11) NULL DEFAULT 0,
  `is_onsale_protection_period` int(11) NULL DEFAULT 0,
  `onsale_protection_end_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '在售保护结束时间',
  `is_vip_protection` int(11) NULL DEFAULT 0,
  `is_time_lock` int(11) NULL DEFAULT 0,
  `time_lock_days` int(11) NULL DEFAULT 0 COMMENT '时间锁定天数',
  `equip_in_test_server` int(11) NULL DEFAULT 0,
  `buyer_in_test_server` int(11) NULL DEFAULT 0,
  `equip_in_allow_take_away_server` int(11) NULL DEFAULT 0,
  `is_weijianding` int(11) NULL DEFAULT 0,
  `is_show_alipay_privilege` int(11) NULL DEFAULT 0,
  `is_seller_redpacket_flag` int(11) NULL DEFAULT 0,
  `is_show_expert_desc` int(11) NULL DEFAULT 0,
  `is_show_special_highlight` int(11) NULL DEFAULT 0,
  `is_xyq_game_role_kunpeng_reach_limit` int(11) NULL DEFAULT 0,
  `equip_onsale_version` int(11) NULL DEFAULT NULL COMMENT '角色上架版本',
  `storage_type` int(11) NULL DEFAULT NULL COMMENT '存储类型',
  `agent_trans_time` int(11) NULL DEFAULT NULL COMMENT '代理传输时间',
  `kol_article_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'KOL文章ID',
  `kol_share_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'KOL分享ID',
  `kol_share_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'KOL分享时间',
  `kol_share_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'KOL分享状态',
  `reco_request_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '推荐请求ID',
  `appointed_roleid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '指定角色ID',
  `play_team_cnt` int(11) NULL DEFAULT NULL COMMENT '游戏团队数量',
  `random_draw_finish_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '随机抽奖完成时间',
  `desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述',
  `large_equip_desc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '大角色描述',
  `desc_sumup` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述总结',
  `desc_sumup_short` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '描述总结简短',
  `diy_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '自定义描述',
  `rec_desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '推荐描述',
  `diy_desc_pay_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '自定义描述支付信息',
  `other_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '其他信息',
  `video_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '视频信息',
  `agg_added_attrs` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '聚合附加属性',
  `dynamic_tags` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '动态标签',
  `highlight` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '高亮信息',
  `tag_key` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '标签键',
  `tag` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '标签',
  `search_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '搜索类型',
  `life_skills` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '生活技能',
  `school_skills` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '师门技能',
  `ju_qing_skills` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '剧情技能',
  `yushoushu_skill` int(11) NULL DEFAULT NULL COMMENT '育兽术技能',
  `raw_data_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '原始数据',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `role_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'normal' COMMENT '角色类型',
  PRIMARY KEY (`eid`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Compact;

SET FOREIGN_KEY_CHECKS = 1;
