var product_name = "xyq";
var server_data = {
    "1": [
        [
            "上海1区",
            "5_4",
            "4",
            "shanghai1qu",
            1,
            "shyq"
        ],
        [
            [
                159,
                "珍宝阁",
                "1_1",
                "zhenbaoge",
                "zbg"
            ],
            [
                163,
                "晚芳亭",
                "2_1",
                "wanfangting",
                "wft"
            ],
            [
                841,
                "灿若星河",
                "3_1",
                "canruoxinghe",
                "crxh"
            ],
            [
                928,
                "苏州河",
                "4_1",
                "suzhouhe",
                "szh"
            ],
            [
                945,
                "华灯初上",
                "5_1",
                "huadengchushang",
                "hdcs"
            ],
            [
                975,
                "新天地",
                "6_1",
                "xintiandi",
                "xtd"
            ],
            [
                994,
                "大闹天宫",
                "7_1",
                "danaotiangong",
                "dntg"
            ],
            [
                1003,
                "城隍庙",
                "8_1",
                "chenghuangmiao",
                "chm"
            ],
            [
                975,
                "长风破浪",
                "9_1",
                "changfengpolang",
                "cfpl"
            ],
            [
                841,
                "龙游四海",
                "10_1",
                "longyousihai",
                "lysh"
            ],
            [
                975,
                "云海雪霜",
                "11_1",
                "yunhaixueshuang",
                "yhxs"
            ]
        ]
    ],
    "2": [
        [
            "广东3区",
            "4_7",
            "40",
            "guangdong3qu",
            2,
            "gdsq"
        ],
        [
            [
                2,
                "罗浮山",
                "1_1",
                "luofushan",
                "lfs"
            ],
            [
                677,
                "广州湾",
                "2_1",
                "guangzhouwan",
                "gzw"
            ],
            [
                677,
                "凤凰台",
                "3_1",
                "fenghuangtai",
                "fht"
            ],
            [
                677,
                "碧海潮生",
                "4_1",
                "bihaichaosheng",
                "bhcs"
            ]
        ]
    ],
    "3": [
        [
            "北京1区",
            "5_1",
            "3",
            "beijing1qu",
            3,
            "bjyq"
        ],
        [
            [
                3,
                "国子监",
                "1_1",
                "guozijian",
                "gzj"
            ],
            [
                155,
                "太和殿",
                "2_1",
                "taihedian",
                "thd"
            ],
            [
                9,
                "紫禁城",
                "3_1",
                "zijincheng",
                "zjc"
            ],
            [
                459,
                "2008",
                "4_1",
                "2008",
                "ellb"
            ],
            [
                527,
                "生日快乐",
                "5_1",
                "shengrikuaile",
                "srkl"
            ],
            [
                699,
                "喜大普奔",
                "6_1",
                "xidapuben",
                "xdpb"
            ],
            [
                769,
                "恭王府",
                "7_1",
                "gongwangfu",
                "gwf"
            ],
            [
                786,
                "五道口",
                "1_2",
                "wudaokou",
                "wdk"
            ],
            [
                838,
                "黄金台",
                "2_2",
                "huangjintai",
                "hjt"
            ],
            [
                810,
                "豪情壮志",
                "3_2",
                "haoqingzhuangzhi",
                "hqzz"
            ],
            [
                851,
                "江山如画",
                "4_2",
                "jiangshanruhua",
                "jsrh"
            ],
            [
                871,
                "繁荣富强",
                "5_2",
                "fanrongfuqiang",
                "frfq"
            ],
            [
                920,
                "香山红叶",
                "6_2",
                "xiangshanhongye",
                "xshy"
            ],
            [
                920,
                "好汉城",
                "7_2",
                "haohancheng",
                "hhc"
            ]
        ]
    ],
    "4": [
        [
            "广东4区",
            "4_8",
            "48",
            "guangdong4qu",
            4,
            "gdsq"
        ],
        [
            [
                358,
                "流花湖",
                "1_1",
                "liuhuahu",
                "lhh"
            ],
            [
                85,
                "白云山",
                "2_1",
                "baiyunshan",
                "bys"
            ],
            [
                82,
                "状元坊",
                "3_1",
                "zhuangyuanfang",
                "zyf"
            ],
            [
                84,
                "流溪河",
                "4_1",
                "liuxihe",
                "lxh"
            ]
        ]
    ],
    "5": [
        [
            "浙江3区",
            "4_3",
            "43",
            "zhejiang3qu",
            5,
            "zjsq"
        ],
        [
            [
                139,
                "普陀山",
                "1_1",
                "putuoshan",
                "pts"
            ],
            [
                138,
                "钱塘江",
                "2_1",
                "qiantangjiang",
                "qtj"
            ],
            [
                804,
                "功成名就",
                "3_1",
                "gongchengmingjiu",
                "gcmj"
            ],
            [
                855,
                "断桥残雪",
                "4_1",
                "duanqiaocanxue",
                "dqcx"
            ],
            [
                995,
                "钱塘观潮",
                "5_1",
                "qiantangguanchao",
                "qtgc"
            ]
        ]
    ],
    "6": [
        [
            "广西2区",
            "1_9",
            "55",
            "guangxi2qu",
            6,
            "gxeq"
        ],
        [
            [
                6,
                "叠彩山",
                "1_1",
                "diecaishan",
                "dcs"
            ],
            [
                6,
                "黄姚古镇",
                "2_1",
                "huangyaoguzhen",
                "hygz"
            ]
        ]
    ],
    "7": [
        [
            "河南2区",
            "2_5",
            "39",
            "henan2qu",
            7,
            "hneq"
        ],
        [
            [
                192,
                "牡丹亭",
                "1_1",
                "mudanting",
                "mdt"
            ],
            [
                193,
                "少室山",
                "2_1",
                "shaoshishan",
                "sss"
            ],
            [
                193,
                "王屋山",
                "3_1",
                "wangwushan",
                "wws"
            ]
        ]
    ],
    "8": [
        [
            "山东2区",
            "6_6",
            "13",
            "shandong2qu",
            8,
            "sdeq"
        ],
        [
            [
                212,
                "水泊梁山",
                "1_1",
                "shuipoliangshan",
                "spls"
            ],
            [
                920,
                "好汉城",
                "2_1",
                "haohancheng",
                "hhc"
            ]
        ]
    ],
    "9": [
        [
            "北京2区",
            "5_2",
            "44",
            "beijing2qu",
            9,
            "bjeq"
        ],
        [
            [
                299,
                "阳光城",
                "1_1",
                "yangguangcheng",
                "ygc"
            ],
            [
                689,
                "万里长城",
                "2_1",
                "wanlichangcheng",
                "wlcc"
            ],
            [
                732,
                "长安街",
                "3_1",
                "changanjie",
                "caj"
            ],
            [
                799,
                "东方巨龙",
                "4_1",
                "dongfangjulong",
                "dfjl"
            ],
            [
                810,
                "天之骄子",
                "5_1",
                "tianzhijiaozi",
                "tzjz"
            ],
            [
                816,
                "龙争虎斗",
                "6_1",
                "longzhenghudou",
                "lzhd"
            ],
            [
                821,
                "顺天府",
                "7_1",
                "shuntianfu",
                "stf"
            ],
            [
                900,
                "天下宝藏",
                "1_2",
                "tianxiabaozang",
                "txbz"
            ],
            [
                816,
                "三吴都会",
                "2_2",
                "sanwuduhui",
                "swdh"
            ],
            [
                821,
                "百战不殆",
                "3_2",
                "baizhanbudai",
                "bzbd"
            ],
            [
                821,
                "千帆竞发",
                "4_2",
                "qianfanjingfa",
                "qfjf"
            ],
            [
                900,
                "乾清宫",
                "5_2",
                "qianqinggong",
                "qqg"
            ],
            [
                935,
                "一生一世",
                "6_2",
                "yishengyishi",
                "ysys"
            ],
            [
                996,
                "长城守望",
                "7_2",
                "changchengshouwang",
                "ccsw"
            ],
            [
                1006,
                "华夏",
                "1_3",
                "huaxia",
                "hx"
            ],
            [
                799,
                "龙图腾",
                "2_3",
                "longtuteng",
                "ltt"
            ]
        ]
    ],
    "10": [
        [
            "福建2区",
            "3_7",
            "45",
            "fujian2qu",
            10,
            "fjeq"
        ],
        [
            [
                304,
                "日光岩",
                "1_1",
                "riguangyan",
                "rgy"
            ],
            [
                234,
                "鼓浪屿",
                "2_1",
                "gulangyu",
                "gly"
            ],
            [
                11,
                "百花村",
                "3_1",
                "baihuacun",
                "bhc"
            ],
            [
                326,
                "齐云楼",
                "4_1",
                "qiyunlou",
                "qyl"
            ]
        ]
    ],
    "11": [
        [
            "广西1区",
            "1_8",
            "20",
            "guangxi1qu",
            11,
            "gxyq"
        ],
        [
            [
                12,
                "明秀园",
                "1_1",
                "mingxiuyuan",
                "mxy"
            ],
            [
                249,
                "青秀山",
                "2_1",
                "qingxiushan",
                "qxs"
            ],
            [
                86,
                "云天宫",
                "3_1",
                "yuntiangong",
                "ytg"
            ],
            [
                925,
                "甲天下",
                "4_1",
                "jiatianxia",
                "jtx"
            ]
        ]
    ],
    "12": [
        [
            "河北1区",
            "2_1",
            "14",
            "hebei1qu",
            12,
            "hbyq"
        ],
        [
            [
                60,
                "缘聚唐城",
                "1_1",
                "yuanjutangcheng",
                "yjtc"
            ],
            [
                482,
                "渤海明珠",
                "2_1",
                "bohaimingzhu",
                "bhmz"
            ],
            [
                931,
                "月亮湖",
                "3_1",
                "yuelianghu",
                "ylh"
            ],
            [
                931,
                "蒹葭苍苍",
                "4_1",
                "jianjiacangcang",
                "jjcc"
            ]
        ]
    ],
    "13": [
        [
            "河北3区",
            "2_3",
            "49",
            "hebei3qu",
            13,
            "hbsq"
        ],
        [
            [
                15,
                "避暑山庄",
                "1_1",
                "bishushanzhuang",
                "bssz"
            ]
        ]
    ],
    "14": [
        [
            "黑龙江区",
            "6_1",
            "35",
            "heilongjiangqu",
            14,
            "hljq"
        ],
        [
            [
                221,
                "雪域天龙",
                "1_1",
                "xueyutianlong",
                "xytl"
            ],
            [
                221,
                "佟佳江",
                "2_1",
                "tongjiajiang",
                "tjj"
            ]
        ]
    ],
    "15": [
        [
            "湖北1区",
            "2_7",
            "16",
            "hubei1qu",
            15,
            "hbyq"
        ],
        [
            [
                94,
                "武当山",
                "1_1",
                "wudangshan",
                "wds"
            ],
            [
                420,
                "昭君台",
                "2_1",
                "zhaojuntai",
                "zjt"
            ],
            [
                871,
                "大江大湖",
                "3_1",
                "dajiangdahu",
                "djdh"
            ],
            [
                94,
                "南天门",
                "4_1",
                "nantianmen",
                "ntm"
            ]
        ]
    ],
    "16": [
        [
            "湖北2区",
            "2_8",
            "42",
            "hubei2qu",
            16,
            "hbeq"
        ],
        [
            [
                420,
                "神农架",
                "1_1",
                "shennongjia",
                "snj"
            ],
            [
                223,
                "黄鹤楼",
                "2_1",
                "huanghelou",
                "hhl"
            ]
        ]
    ],
    "17": [
        [
            "湖南区",
            "2_9",
            "26",
            "hunanqu",
            17,
            "hnq"
        ],
        [
            [
                275,
                "橘子洲",
                "1_1",
                "juzizhou",
                "jzz"
            ],
            [
                96,
                "洞庭湖",
                "2_1",
                "dongtinghu",
                "dth"
            ],
            [
                925,
                "风华正茂",
                "3_1",
                "fenghuazhengmao",
                "fhzm"
            ],
            [
                975,
                "云海雪霜",
                "4_1",
                "yunhaixueshuang",
                "yhxs"
            ],
            [
                925,
                "甲天下",
                "5_1",
                "jiatianxia",
                "jtx"
            ]
        ]
    ],
    "19": [
        [
            "天津区",
            "7_1",
            "60",
            "tianjinqu",
            19,
            "tjq"
        ],
        [
            [
                55,
                "精武门",
                "1_1",
                "jingwumen",
                "jwm"
            ]
        ]
    ],
    "20": [
        [
            "吉林区",
            "6_2",
            "36",
            "jilinqu",
            20,
            "jlq"
        ],
        [
            [
                221,
                "佟佳江",
                "1_1",
                "tongjiajiang",
                "tjj"
            ]
        ]
    ],
    "21": [
        [
            "江苏1区",
            "3_1",
            "9",
            "jiangsu1qu",
            21,
            "jsyq"
        ],
        [
            [
                101,
                "文昌阁",
                "1_1",
                "wenchangge",
                "wcg"
            ],
            [
                104,
                "雨花台",
                "2_1",
                "yuhuatai",
                "yht"
            ],
            [
                677,
                "凤凰台",
                "3_1",
                "fenghuangtai",
                "fht"
            ],
            [
                855,
                "天下文枢",
                "4_1",
                "tianxiawenshu",
                "txws"
            ],
            [
                933,
                "寒山寺",
                "5_1",
                "hanshansi",
                "hss"
            ],
            [
                936,
                "苏州园林",
                "6_1",
                "suzhouyuanlin",
                "szyl"
            ],
            [
                936,
                "金陵",
                "7_1",
                "jinling",
                "jl"
            ],
            [
                957,
                "秦淮风光",
                "8_1",
                "qinhuaifengguang",
                "qhfg"
            ],
            [
                957,
                "空山新雨",
                "9_1",
                "kongshanxinyu",
                "ksxy"
            ],
            [
                971,
                "水调歌头",
                "10_1",
                "shuidiaogetou",
                "sdgt"
            ],
            [
                981,
                "十里桃花",
                "11_1",
                "shilitaohua",
                "slth"
            ],
            [
                993,
                "齐天大圣",
                "12_1",
                "qitiandasheng",
                "qtds"
            ],
            [
                999,
                "雪满关山",
                "13_1",
                "xuemanguanshan",
                "xmgs"
            ]
        ]
    ],
    "22": [
        [
            "江苏2区",
            "3_2",
            "38",
            "jiangsu2qu",
            22,
            "jseq"
        ],
        [
            [
                105,
                "夫子庙",
                "1_1",
                "fuzimiao",
                "fzm"
            ],
            [
                352,
                "姑苏城",
                "2_1",
                "gusucheng",
                "gsc"
            ],
            [
                898,
                "枫桥夜泊",
                "3_1",
                "fengqiaoyepo",
                "fqyp"
            ]
        ]
    ],
    "23": [
        [
            "江苏3区",
            "3_3",
            "51",
            "jiangsu3qu",
            23,
            "jssq"
        ],
        [
            [
                26,
                "花果山",
                "1_1",
                "huaguoshan",
                "hgs"
            ],
            [
                462,
                "镇淮楼",
                "2_1",
                "zhenhuailou",
                "zhl"
            ],
            [
                902,
                "燕子矶",
                "3_1",
                "yanziji",
                "yzj"
            ],
            [
                933,
                "南禅寺",
                "4_1",
                "nanchansi",
                "ncs"
            ],
            [
                930,
                "烟花三月",
                "5_1",
                "yanhuasanyue",
                "yhsy"
            ],
            [
                930,
                "秋分",
                "6_1",
                "qiufen",
                "qf"
            ]
        ]
    ],
    "24": [
        [
            "江西区",
            "3_5",
            "25",
            "jiangxiqu",
            24,
            "jxq"
        ],
        [
            [
                270,
                "庐山胜境",
                "1_1",
                "lushanshengjing",
                "lssj"
            ]
        ]
    ],
    "25": [
        [
            "辽宁1区",
            "6_3",
            "15",
            "liaoning1qu",
            25,
            "lnyq"
        ],
        [
            [
                367,
                "星海湾",
                "1_1",
                "xinghaiwan",
                "xhw"
            ]
        ]
    ],
    "26": [
        [
            "山东1区",
            "6_5",
            "33",
            "shandong1qu",
            26,
            "sdyq"
        ],
        [
            [
                211,
                "东岳泰山",
                "1_1",
                "dongyuetaishan",
                "dyts"
            ],
            [
                94,
                "南天门",
                "2_1",
                "nantianmen",
                "ntm"
            ],
            [
                669,
                "青岛栈桥",
                "3_1",
                "qingdaozhanqiao",
                "qdzq"
            ],
            [
                681,
                "东海崂山",
                "4_1",
                "donghailaoshan",
                "dhls"
            ],
            [
                821,
                "千帆竞发",
                "5_1",
                "qianfanjingfa",
                "qfjf"
            ],
            [
                934,
                "凌绝顶",
                "6_1",
                "lingjueding",
                "ljd"
            ],
            [
                934,
                "临江仙",
                "7_1",
                "linjiangxian",
                "ljx"
            ],
            [
                934,
                "五岳独尊",
                "1_2",
                "wuyueduzun",
                "wydz"
            ],
            [
                1004,
                "春风得意",
                "2_2",
                "chunfengdeyi",
                "cfdy"
            ]
        ]
    ],
    "27": [
        [
            "山东3区",
            "6_7",
            "37",
            "shandong3qu",
            27,
            "sdsq"
        ],
        [
            [
                33,
                "蓬莱岛",
                "1_1",
                "penglaidao",
                "pld"
            ],
            [
                857,
                "壮气凌云",
                "2_1",
                "zhuangqilingyun",
                "zqly"
            ],
            [
                857,
                "十里金沙",
                "3_1",
                "shilijinsha",
                "sljs"
            ],
            [
                857,
                "三水荷花",
                "4_1",
                "sanshuihehua",
                "sshh"
            ],
            [
                857,
                "洪崖洞",
                "5_1",
                "hongyadong",
                "hyd"
            ]
        ]
    ],
    "28": [
        [
            "山东4区",
            "6_8",
            "47",
            "shandong4qu",
            28,
            "sdsq"
        ],
        [
            [
                207,
                "大明湖",
                "1_1",
                "daminghu",
                "dmh"
            ],
            [
                443,
                "沂水雪山",
                "2_1",
                "yishuixueshan",
                "ysxs"
            ],
            [
                934,
                "灵山湾",
                "3_1",
                "lingshanwan",
                "lsw"
            ]
        ]
    ],
    "29": [
        [
            "山东5区",
            "6_9",
            "54",
            "shandong5qu",
            29,
            "sdwq"
        ],
        [
            [
                34,
                "玉皇顶",
                "1_1",
                "yuhuangding",
                "yhd"
            ],
            [
                407,
                "曲阜孔庙",
                "2_1",
                "qufukongmiao",
                "qfkm"
            ],
            [
                657,
                "威海卫",
                "3_1",
                "weihaiwei",
                "whw"
            ]
        ]
    ],
    "30": [
        [
            "山西区",
            "1_2",
            "19",
            "shanxiqu",
            30,
            "sxq"
        ],
        [
            [
                421,
                "雁门关",
                "1_1",
                "yanmenguan",
                "ymg"
            ]
        ]
    ],
    "31": [
        [
            "陕西区",
            "1_3",
            "12",
            "shanxiqu",
            31,
            "sxq"
        ],
        [
            [
                200,
                "大雁塔",
                "1_1",
                "dayanta",
                "dyt"
            ],
            [
                203,
                "西岳华山",
                "2_1",
                "xiyuehuashan",
                "xyhs"
            ],
            [
                928,
                "岁岁长安",
                "3_1",
                "suisuichangan",
                "ssca"
            ]
        ]
    ],
    "32": [
        [
            "上海2区",
            "5_5",
            "22",
            "shanghai2qu",
            32,
            "sheq"
        ],
        [
            [
                38,
                "东方明珠",
                "1_1",
                "dongfangmingzhu",
                "dfmz"
            ],
            [
                622,
                "徐家汇",
                "2_1",
                "xujiahui",
                "xjh"
            ],
            [
                855,
                "四海升平",
                "3_1",
                "sihaishengping",
                "shsp"
            ],
            [
                855,
                "天下文枢",
                "4_1",
                "tianxiawenshu",
                "txws"
            ],
            [
                855,
                "腾云驾雾",
                "5_1",
                "tengyunjiawu",
                "tyjw"
            ],
            [
                855,
                "桃花坞",
                "6_1",
                "taohuawu",
                "thw"
            ]
        ]
    ],
    "33": [
        [
            "深圳2区",
            "3_9",
            "52",
            "shenzhen2qu",
            33,
            "szeq"
        ],
        [
            [
                412,
                "梧桐山",
                "1_1",
                "wutongshan",
                "wts"
            ],
            [
                344,
                "小梅沙",
                "2_1",
                "xiaomeisha",
                "xms"
            ],
            [
                39,
                "世界之窗",
                "3_1",
                "shijiezhichuang",
                "sjzc"
            ]
        ]
    ],
    "34": [
        [
            "四川1区",
            "1_4",
            "23",
            "sichuan1qu",
            34,
            "scyq"
        ],
        [
            [
                263,
                "嘉陵江",
                "1_1",
                "jialingjiang",
                "jlj"
            ],
            [
                40,
                "成都府",
                "2_1",
                "chengdufu",
                "cdf"
            ],
            [
                918,
                "三星堆",
                "3_1",
                "sanxingdui",
                "sxd"
            ],
            [
                960,
                "康定情歌",
                "4_1",
                "kangdingqingge",
                "kdqg"
            ],
            [
                918,
                "黑熊谷",
                "5_1",
                "heixionggu",
                "hxg"
            ]
        ]
    ],
    "35": [
        [
            "浙江4区",
            "4_4",
            "50",
            "zhejiang4qu",
            35,
            "zjsq"
        ],
        [
            [
                377,
                "绍兴兰亭",
                "1_1",
                "shaoxinglanting",
                "sxlt"
            ],
            [
                416,
                "绍兴鉴湖",
                "2_1",
                "shaoxingjianhu",
                "sxjh"
            ],
            [
                750,
                "烟雨江南",
                "3_1",
                "yanyujiangnan",
                "yyjn"
            ],
            [
                881,
                "好运岛",
                "4_1",
                "haoyundao",
                "hyd"
            ],
            [
                950,
                "春色满园",
                "5_1",
                "chunsemanyuan",
                "csmy"
            ]
        ]
    ],
    "36": [
        [
            "贵州区",
            "1_7",
            "57",
            "guizhouqu",
            36,
            "gzq"
        ],
        [
            [
                285,
                "红枫湖",
                "1_1",
                "hongfenghu",
                "hfh"
            ]
        ]
    ],
    "37": [
        [
            "深圳1区",
            "3_8",
            "21",
            "shenzhen1qu",
            37,
            "szyq"
        ],
        [
            [
                116,
                "大观园",
                "1_1",
                "daguanyuan",
                "dgy"
            ]
        ]
    ],
    "38": [
        [
            "时光",
            "7_8",
            "32",
            "shiguang",
            38,
            "sg"
        ],
        [
            [
                45,
                "花样年华",
                "1_1",
                "huayangnianhua",
                "hynh"
            ]
        ]
    ],
    "39": [
        [
            "华南区",
            "7_2",
            "6",
            "huananqu",
            39,
            "hnq"
        ],
        [
            [
                173,
                "逍遥城",
                "1_1",
                "xiaoyaocheng",
                "xyc"
            ],
            [
                625,
                "钓鱼岛",
                "2_1",
                "diaoyudao",
                "dyd"
            ],
            [
                173,
                "侠客岛",
                "3_1",
                "xiakedao",
                "xkd"
            ]
        ]
    ],
    "40": [
        [
            "内蒙区",
            "1_1",
            "17",
            "neimengqu",
            40,
            "nmq"
        ],
        [
            [
                229,
                "雄鹰岭",
                "1_1",
                "xiongyingling",
                "xyl"
            ]
        ]
    ],
    "41": [
        [
            "福建1区",
            "3_6",
            "18",
            "fujian1qu",
            41,
            "fjyq"
        ],
        [
            [
                305,
                "朱紫坊",
                "1_1",
                "zhuzifang",
                "zzf"
            ],
            [
                305,
                "凌云殿",
                "2_1",
                "lingyundian",
                "lyd"
            ],
            [
                928,
                "彩云归",
                "3_1",
                "caiyungui",
                "cyg"
            ],
            [
                928,
                "岁岁长安",
                "4_1",
                "suisuichangan",
                "ssca"
            ],
            [
                928,
                "苏州河",
                "5_1",
                "suzhouhe",
                "szh"
            ]
        ]
    ],
    "42": [
        [
            "安徽1区",
            "3_4",
            "24",
            "anhui1qu",
            42,
            "ahyq"
        ],
        [
            [
                417,
                "紫蓬山",
                "1_1",
                "zipengshan",
                "zps"
            ],
            [
                266,
                "慈光阁",
                "2_1",
                "ciguangge",
                "cgg"
            ],
            [
                930,
                "秋分",
                "3_1",
                "qiufen",
                "qf"
            ]
        ]
    ],
    "43": [
        [
            "广东2区",
            "4_6",
            "8",
            "guangdong2qu",
            43,
            "gdeq"
        ],
        [
            [
                79,
                "如意岛",
                "1_1",
                "ruyidao",
                "ryd"
            ],
            [
                77,
                "进贤门",
                "2_1",
                "jinxianmen",
                "jxm"
            ],
            [
                78,
                "万绿湖",
                "3_1",
                "wanluhu",
                "wlh"
            ],
            [
                79,
                "七星岩",
                "4_1",
                "qixingyan",
                "qxy"
            ]
        ]
    ],
    "44": [
        [
            "云南区",
            "1_6",
            "29",
            "yunnanqu",
            44,
            "ynq"
        ],
        [
            [
                127,
                "彩云之南",
                "1_1",
                "caiyunzhinan",
                "cyzn"
            ],
            [
                130,
                "蝴蝶泉",
                "2_1",
                "hudiequan",
                "hdq"
            ]
        ]
    ],
    "45": [
        [
            "追忆",
            "7_5",
            "2",
            "zhuiyi",
            45,
            "zy"
        ],
        [
            [
                149,
                "再续前缘",
                "1_1",
                "zaixuqianyuan",
                "zxqy"
            ],
            [
                150,
                "梦回望月",
                "2_1",
                "menghuiwangyue",
                "mhwy"
            ],
            [
                901,
                "2020",
                "3_1",
                "2020",
                "elel"
            ],
            [
                954,
                "一生所爱",
                "4_1",
                "yishengsuoai",
                "yssa"
            ],
            [
                962,
                "天命之路",
                "5_1",
                "tianmingzhilu",
                "tmzl"
            ]
        ]
    ],
    "47": [
        [
            "广东1区",
            "4_5",
            "34",
            "guangdong1qu",
            47,
            "gdyq"
        ],
        [
            [
                72,
                "湖光岩",
                "1_1",
                "huguangyan",
                "hgy"
            ],
            [
                857,
                "三水荷花",
                "2_1",
                "sanshuihehua",
                "sshh"
            ],
            [
                857,
                "十里银滩",
                "3_1",
                "shiliyintan",
                "slyt"
            ],
            [
                942,
                "二沙岛",
                "4_1",
                "ershadao",
                "esd"
            ],
            [
                857,
                "太公岛",
                "5_1",
                "taigongdao",
                "tgd"
            ]
        ]
    ],
    "48": [
        [
            "河北2区",
            "2_2",
            "41",
            "hebei2qu",
            48,
            "hbeq"
        ],
        [
            [
                334,
                "燕塞湖",
                "1_1",
                "yansehu",
                "ysh"
            ],
            [
                215,
                "燕赵风云",
                "2_1",
                "yanzhaofengyun",
                "yzfy"
            ],
            [
                931,
                "观沧海",
                "3_1",
                "guancanghai",
                "gch"
            ]
        ]
    ],
    "49": [
        [
            "河南1区",
            "2_4",
            "11",
            "henan1qu",
            49,
            "hnyq"
        ],
        [
            [
                413,
                "少林寺",
                "1_1",
                "shaolinsi",
                "sls"
            ],
            [
                197,
                "中岳嵩山",
                "2_1",
                "zhongyuesongshan",
                "zyss"
            ],
            [
                199,
                "汴梁城",
                "3_1",
                "bianliangcheng",
                "blc"
            ],
            [
                799,
                "龙图腾",
                "4_1",
                "longtuteng",
                "ltt"
            ],
            [
                945,
                "河图洛书",
                "5_1",
                "hetuluoshu",
                "htls"
            ],
            [
                972,
                "九曲黄河",
                "6_1",
                "jiuquhuanghe",
                "jqhh"
            ],
            [
                945,
                "华灯初上",
                "7_1",
                "huadengchushang",
                "hdcs"
            ],
            [
                997,
                "鱼跃龙门",
                "8_1",
                "yuyuelongmen",
                "yylm"
            ]
        ]
    ],
    "50": [
        [
            "河南3区",
            "2_6",
            "58",
            "henan3qu",
            50,
            "hnsq"
        ],
        [
            [
                414,
                "南阳府",
                "1_1",
                "nanyangfu",
                "nyf"
            ],
            [
                898,
                "逐鹿中原",
                "2_1",
                "zhuluzhongyuan",
                "zlzy"
            ],
            [
                898,
                "枫桥夜泊",
                "3_1",
                "fengqiaoyepo",
                "fqyp"
            ]
        ]
    ],
    "51": [
        [
            "辽宁2区",
            "6_4",
            "46",
            "liaoning2qu",
            51,
            "lneq"
        ],
        [
            [
                367,
                "医巫闾山",
                "1_1",
                "yiwulvshan",
                "ywls"
            ]
        ]
    ],
    "52": [
        [
            "四川2区",
            "1_5",
            "5",
            "sichuan2qu",
            52,
            "sceq"
        ],
        [
            [
                167,
                "文殊院",
                "1_1",
                "wenshuyuan",
                "wsy"
            ],
            [
                123,
                "德阳文庙",
                "2_1",
                "deyangwenmiao",
                "dywm"
            ],
            [
                918,
                "黑熊谷",
                "3_1",
                "heixionggu",
                "hxg"
            ],
            [
                941,
                "绿茵风采",
                "4_1",
                "lvyinfengcai",
                "lyfc"
            ],
            [
                952,
                "寻梦古蜀",
                "5_1",
                "xunmenggushu",
                "xmgs"
            ],
            [
                1009,
                "老君阁",
                "6_1",
                "laojunge",
                "ljg"
            ]
        ]
    ],
    "54": [
        [
            "浙江1区",
            "4_1",
            "28",
            "zhejiang1qu",
            54,
            "zjyq"
        ],
        [
            [
                133,
                "台州湾",
                "1_1",
                "taizhouwan",
                "tzw"
            ],
            [
                132,
                "西栅老街",
                "2_1",
                "xishanlaojie",
                "xslj"
            ],
            [
                712,
                "文澜阁",
                "3_1",
                "wenlange",
                "wlg"
            ],
            [
                856,
                "龙泉山",
                "4_1",
                "longquanshan",
                "lqs"
            ],
            [
                841,
                "龙游四海",
                "5_1",
                "longyousihai",
                "lysh"
            ],
            [
                855,
                "桃花坞",
                "6_1",
                "taohuawu",
                "thw"
            ],
            [
                932,
                "西塘古镇",
                "7_1",
                "xitangguzhen",
                "xtgz"
            ],
            [
                932,
                "嘉兴南湖",
                "8_1",
                "jiaxingnanhu",
                "jxnh"
            ],
            [
                953,
                "团团圆圆",
                "9_1",
                "tuantuanyuanyuan",
                "ttyy"
            ],
            [
                971,
                "比翼飞",
                "10_1",
                "biyifei",
                "byf"
            ],
            [
                987,
                "西湖醋鱼",
                "11_1",
                "xihucuyu",
                "xhcy"
            ],
            [
                992,
                "一战成名",
                "12_1",
                "yizhanchengming",
                "yzcm"
            ],
            [
                953,
                "一路有你",
                "13_1",
                "yiluyouni",
                "ylyn"
            ],
            [
                1007,
                "南屏晚钟",
                "14_1",
                "nanpingwanzhong",
                "npwz"
            ]
        ]
    ],
    "55": [
        [
            "浙江2区",
            "4_2",
            "10",
            "zhejiang2qu",
            55,
            "zjeq"
        ],
        [
            [
                137,
                "苏堤春晓",
                "1_1",
                "sudichunxiao",
                "sdcx"
            ],
            [
                378,
                "灵隐寺",
                "2_1",
                "lingyinsi",
                "lys"
            ],
            [
                677,
                "碧海潮生",
                "3_1",
                "bihaichaosheng",
                "bhcs"
            ],
            [
                758,
                "西湖龙井",
                "4_1",
                "xihulongjing",
                "xhlj"
            ],
            [
                881,
                "彩凤鸣岐",
                "5_1",
                "caifengmingqi",
                "cfmq"
            ],
            [
                881,
                "忆江南",
                "6_1",
                "yijiangnan",
                "yjn"
            ],
            [
                950,
                "西湖映月",
                "7_1",
                "xihuyingyue",
                "xhyy"
            ],
            [
                965,
                "山外青山",
                "8_1",
                "shanwaiqingshan",
                "swqs"
            ],
            [
                965,
                "九天揽月",
                "9_1",
                "jiutianlanyue",
                "jtly"
            ],
            [
                998,
                "壮志凌云",
                "10_1",
                "zhuangzhilingyun",
                "zzly"
            ],
            [
                1002,
                "蛇来运转",
                "11_1",
                "shelaiyunzhuan",
                "slyz"
            ]
        ]
    ],
    "56": [
        [
            "重庆区",
            "5_6",
            "31",
            "chongqingqu",
            56,
            "cqq"
        ],
        [
            [
                146,
                "解放碑",
                "1_1",
                "jiefangbei",
                "jfb"
            ],
            [
                482,
                "茶山竹海",
                "2_1",
                "chashanzhuhai",
                "cszh"
            ],
            [
                857,
                "洪崖洞",
                "3_1",
                "hongyadong",
                "hyd"
            ],
            [
                857,
                "神女峰",
                "4_1",
                "shennvfeng",
                "snf"
            ],
            [
                857,
                "小三峡",
                "5_1",
                "xiaosanxia",
                "xsx"
            ],
            [
                482,
                "渤海明珠",
                "6_1",
                "bohaimingzhu",
                "bhmz"
            ]
        ]
    ],
    "57": [
        [
            "海外专区",
            "7_4",
            "30",
            "haiwaizhuanqu",
            57,
            "hwzq"
        ],
        [
            [
                173,
                "侠客岛",
                "1_1",
                "xiakedao",
                "xkd"
            ]
        ]
    ],
    "58": [
        [
            "无与伦比",
            "7_3",
            "61",
            "wuyulunbi",
            58,
            "wylb"
        ],
        [
            [
                554,
                "兰亭序",
                "1_1",
                "lantingxu",
                "ltx"
            ],
            [
                558,
                "青花瓷",
                "2_1",
                "qinghuaci",
                "qhc"
            ],
            [
                559,
                "本草纲目",
                "3_1",
                "bencaogangmu",
                "bcgm"
            ],
            [
                558,
                "菊花台",
                "4_1",
                "juhuatai",
                "jht"
            ],
            [
                579,
                "千里之外",
                "5_1",
                "qianlizhiwai",
                "qlzw"
            ],
            [
                583,
                "龙拳",
                "6_1",
                "longquan",
                "lq"
            ],
            [
                584,
                "将军",
                "7_1",
                "jiangjun",
                "jj"
            ],
            [
                705,
                "龙马精神",
                "1_2",
                "longmajingshen",
                "lmjs"
            ],
            [
                976,
                "梦幻西游",
                "2_2",
                "menghuanxiyou",
                "mhxy"
            ],
            [
                982,
                "龙的传人",
                "3_2",
                "longdechuanren",
                "ldcr"
            ]
        ]
    ],
    "60": [
        [
            "天下无双",
            "5_7",
            "67",
            "tianxiawushuang",
            60,
            "txws"
        ],
        [
            [
                723,
                "群星璀璨",
                "1_1",
                "qunxingcuican",
                "qxcc"
            ],
            [
                730,
                "金戈铁马",
                "2_1",
                "jingetiema",
                "jgtm"
            ],
            [
                866,
                "聚圣三界",
                "3_1",
                "jushengsanjie",
                "jssj"
            ],
            [
                785,
                "逍遥三界",
                "4_1",
                "xiaoyaosanjie",
                "xysj"
            ],
            [
                791,
                "诗情画意",
                "5_1",
                "shiqinghuayi",
                "sqhy"
            ],
            [
                795,
                "超凡入圣",
                "6_1",
                "chaofanrusheng",
                "cfrs"
            ],
            [
                866,
                "纵横驰骋",
                "7_1",
                "zonghengchicheng",
                "zhcc"
            ],
            [
                894,
                "金榜题名",
                "1_2",
                "jinbangtiming",
                "jbtm"
            ],
            [
                866,
                "俊秀河山",
                "2_2",
                "junxiuheshan",
                "jxhs"
            ],
            [
                894,
                "弈决风云",
                "3_2",
                "yijuefengyun",
                "yjfy"
            ],
            [
                866,
                "天地无极",
                "4_2",
                "tiandiwuji",
                "tdwj"
            ],
            [
                894,
                "撼海狂龙",
                "5_2",
                "hanhaikuanglong",
                "hhkl"
            ],
            [
                967,
                "九黎之影",
                "6_2",
                "jiulizhiying",
                "jlzy"
            ],
            [
                984,
                "盖世英雄",
                "7_2",
                "gaishiyingxiong",
                "gsyx"
            ]
        ]
    ],
    "61": [
        [
            "笑傲三界",
            "5_8",
            "70",
            "xiaoaosanjie",
            61,
            "xasj"
        ],
        [
            [
                807,
                "花好月圆",
                "1_1",
                "huahaoyueyuan",
                "hhyy"
            ],
            [
                811,
                "华山论剑",
                "2_1",
                "huashanlunjian",
                "hslj"
            ],
            [
                811,
                "上古神器",
                "3_1",
                "shanggushenqi",
                "sgsq"
            ],
            [
                811,
                "群雄争霸",
                "4_1",
                "qunxiongzhengba",
                "qxzb"
            ],
            [
                868,
                "纵横天下",
                "5_1",
                "zonghengtianxia",
                "zhtx"
            ],
            [
                855,
                "腾云驾雾",
                "6_1",
                "tengyunjiawu",
                "tyjw"
            ],
            [
                856,
                "龙吟九天",
                "7_1",
                "longyinjiutian",
                "lyjt"
            ],
            [
                856,
                "绝代天骄",
                "1_2",
                "juedaitianjiao",
                "jdtj"
            ],
            [
                811,
                "泱泱大风",
                "2_2",
                "yangyangdafeng",
                "yydf"
            ],
            [
                856,
                "龙泉山",
                "3_2",
                "longquanshan",
                "lqs"
            ],
            [
                975,
                "长风破浪",
                "4_2",
                "changfengpolang",
                "cfpl"
            ],
            [
                979,
                "龙腾九霄",
                "5_2",
                "longtengjiuxiao",
                "ltjx"
            ],
            [
                985,
                "五福临门",
                "6_2",
                "wufulinmen",
                "wflm"
            ],
            [
                990,
                "双龙之战",
                "7_2",
                "shuanglongzhizhan",
                "slzz"
            ],
            [
                1001,
                "平安喜乐",
                "1_3",
                "pinganxile",
                "paxl"
            ],
            [
                1008,
                "仗剑天涯",
                "2_3",
                "zhangjiantianya",
                "zjty"
            ]
        ]
    ],
    "62": [
        [
            "名扬三界",
            "5_9",
            "71",
            "mingyangsanjie",
            62,
            "mysj"
        ],
        [
            [
                868,
                "文韬武略",
                "1_1",
                "wentaowulue",
                "wtwl"
            ],
            [
                878,
                "洋光闪耀",
                "2_1",
                "yangguangshanyao",
                "ygsy"
            ],
            [
                882,
                "国泰民安",
                "3_1",
                "guotaiminan",
                "gtma"
            ],
            [
                878,
                "剑胆孤心",
                "4_1",
                "jiandanguxin",
                "jdgx"
            ],
            [
                878,
                "畅游三界",
                "5_1",
                "changyousanjie",
                "cysj"
            ],
            [
                911,
                "恭喜发财",
                "6_1",
                "gongxifacai",
                "gxfc"
            ],
            [
                882,
                "绮梦长安",
                "7_1",
                "qimengchangan",
                "qmca"
            ],
            [
                939,
                "卧虎藏龙",
                "8_1",
                "wohucanglong",
                "whcl"
            ],
            [
                939,
                "为人师表",
                "9_1",
                "weirenshibiao",
                "wrsb"
            ],
            [
                939,
                "四季发财",
                "10_1",
                "sijifacai",
                "sjfc"
            ],
            [
                971,
                "万里华夏",
                "11_1",
                "wanlihuaxia",
                "wlhx"
            ],
            [
                977,
                "宝藏之夜",
                "12_1",
                "baozangzhiye",
                "bzzy"
            ],
            [
                983,
                "春心萌动",
                "13_1",
                "chunxinmengdong",
                "cxmd"
            ],
            [
                971,
                "比翼飞",
                "14_1",
                "biyifei",
                "byf"
            ],
            [
                971,
                "水调歌头",
                "15_1",
                "shuidiaogetou",
                "sdgt"
            ],
            [
                1005,
                "天外飞仙",
                "16_1",
                "tianwaifeixian",
                "twfx"
            ],
            [
                868,
                "纵横天下",
                "17_1",
                "zonghengtianxia",
                "zhtx"
            ]
        ]
    ],
    "63": [
        [
            "山河社稷",
            "5_10",
            "72",
            "shanhesheji",
            63,
            "shsj"
        ],
        [
            [
                892,
                "长安城",
                "1_1",
                "changancheng",
                "cac"
            ],
            [
                902,
                "东海湾",
                "2_1",
                "donghaiwan",
                "dhw"
            ],
            [
                926,
                "大唐官府",
                "3_1",
                "datangguanfu",
                "dtgf"
            ],
            [
                989,
                "东海龙宫",
                "4_1",
                "donghailonggong",
                "dhlg"
            ],
            [
                902,
                "燕子矶",
                "5_1",
                "yanziji",
                "yzj"
            ]
        ]
    ],
    "66": [
        [
            "良辰美景",
            "7_6",
            "75",
            "liangchenmeijing",
            66,
            "lcmj"
        ],
        [
            [
                941,
                "水云归",
                "1_1",
                "shuiyungui",
                "syg"
            ],
            [
                953,
                "一路有你",
                "2_1",
                "yiluyouni",
                "ylyn"
            ],
            [
                952,
                "玉兔呈祥",
                "3_1",
                "yutuchengxiang",
                "ytcx"
            ],
            [
                960,
                "女儿情",
                "4_1",
                "nverqing",
                "neq"
            ],
            [
                967,
                "斗战胜佛",
                "5_1",
                "douzhanshengfo",
                "dzsf"
            ],
            [
                980,
                "福星高照",
                "6_1",
                "fuxinggaozhao",
                "fxgz"
            ],
            [
                941,
                "绿茵风采",
                "7_1",
                "lvyinfengcai",
                "lyfc"
            ],
            [
                986,
                "热爱为伍",
                "8_1",
                "reaiweiwu",
                "raww"
            ],
            [
                960,
                "康定情歌",
                "9_1",
                "kangdingqingge",
                "kdqg"
            ],
            [
                952,
                "寻梦古蜀",
                "10_1",
                "xunmenggushu",
                "xmgs"
            ],
            [
                991,
                "巫山曲",
                "11_1",
                "wushanqu",
                "wsq"
            ],
            [
                967,
                "九黎之影",
                "12_1",
                "jiulizhiying",
                "jlzy"
            ],
            [
                1010,
                "一见钟情",
                "13_1",
                "yijianzhongqing",
                "yjzq"
            ]
        ]
    ],
    "67": [
        [
            "北京3区",
            "5_3",
            "77",
            "beijing3qu",
            67,
            "bjsq"
        ],
        [
            [
                962,
                "水木清华",
                "1_1",
                "shuimuqinghua",
                "smqh"
            ],
            [
                969,
                "紫禁之巅",
                "2_1",
                "zijinzhidian",
                "zjzd"
            ],
            [
                988,
                "气贯长虹",
                "3_1",
                "qiguanchanghong",
                "qgch"
            ],
            [
                962,
                "天命之路",
                "4_1",
                "tianmingzhilu",
                "tmzl"
            ]
        ]
    ],
    "68": [
        [
            "星辰大海",
            "7_7",
            "78",
            "xingchendahai",
            68,
            "xcdh"
        ],
        [
            [
                1000,
                "友情岁月",
                "1_1",
                "youqingsuiyue",
                "yqsy"
            ]
        ]
    ]
}