var cbg_tracer={};cbg_tracer.session={effectiveDuration:30*60*1000,get:function get(){if(window.sessionStorage){var valueString=window.sessionStorage.getItem('CBG_TRACE_SESSION');}else{var valueString=window.CBG_TRACE_SESSION;}
if(valueString){try{var obj=JSON.decode(valueString);var sid=obj.sid,expireTime=obj.expireTime;if(Date.now()<=expireTime){return sid;}}catch(err){console.error(err);}}
var result=cbg_tracer.session.reset();return result.sid;},reset:function reset(){var obj={sid:cbg_tracer.uuid(),expireTime:Date.now()+cbg_tracer.session.effectiveDuration};var valueString=JSON.encode(obj);if(window.sessionStorage){window.sessionStorage.setItem('CBG_TRACE_SESSION',valueString);}else{window.CBG_TRACE_SESSION=valueString;}
Cookie.write('trace_session_id',obj.sid);return obj;},update:function update(){var sid=cbg_tracer.session.get();var obj={sid:sid,expireTime:Date.now()+cbg_tracer.session.effectiveDuration};var valueString=JSON.encode(obj);if(window.sessionStorage){window.sessionStorage.setItem('CBG_TRACE_SESSION',valueString);}else{window.CBG_TRACE_SESSION=valueString;}
Cookie.write('trace_session_id',obj.sid);},init:function init(){if(document.addEventListener){document.addEventListener('touchstart',cbg_tracer.session.update,true);document.addEventListener('mousedown',cbg_tracer.session.update,true);}else{document.addEvent('touchstart',cbg_tracer.session.update);document.addEvent('mousedown',cbg_tracer.session.update);}}};cbg_tracer.uuid=function(){var pick=function(value,length){var base16=value.toString(16),len=base16.length-1,str='';while(str.length<length){str+=base16.substr(Math.round(random(0,len)),1);}
return str;};function random(){var r=Math.random(),args=arguments,length=args.length;if(length===1){r*=args[0];}else if(length===2){r=Math.round(r*(args[1]-args[0]))+args[0];}
return r;}
function rand(length,type){if(length<1){return 0;}
var str='',r,isNum=(type==='num');while(str.length<length){r=Math.floor(Date.now()*random()*999);if(!isNum){r=r.toString(16);}
str+=r;}
return str.substr(0,length);}
function add0(obj,length){if(!obj){return '0';}
var str=String(obj),times=length-str.length;return repeat('0',times)+str;}
function repeat(string,times){return(times<1)?'':(new Array(times+1).join(string));}
var t=Date.now(),t16=add0(t.toString(16),12),u1=t16.substr(0,8),u2=t16.substr(8,4),u3=pick(t,4),u4=pick(rand(t%97),2),u5=pick(rand(t%89),2),u6=pick(rand(4),1)+pick(rand(8),1)+pick(rand(16),2)+pick(rand(32),2)+pick(rand(64),3)+pick(rand(128),3),id='';id=u1+'-'+u2+'-'+u3+'-'+u4+u5+'-'+u6;return id.toUpperCase();};cbg_tracer.init=function(){var click_event_log_handler=function(e){var target=e.target;var tid=target.get('tid');if(!tid){var target=target.getParent('*[tid]');if(!target){return;}}
var config=cbg_tracer.get_common_trace_info();config.push(['kind','S_#kind_tree_panel ul .on:not(.off)']);var attrs=cbg_tracer.get_attrs(config);var text=target.getAttribute('data_trace_text')||target.get('text');if(!text){text=target.get('value');}
if(!text){text='-';}
text=text.trim();attrs.push(['tid',target.get('tid')]);attrs.push(['text',text]);var json=target.getAttribute('data_trace_json');if(json){try{json=JSON.decode(json);}catch(e){}}
if(json&&typeof json==='object'){Object.keys(json).forEach(function(key){attrs.push([key,json[key]]);});}
var action_url=target.getAttribute('data_trace_action_url');if(action_url){attrs.push(['action_url',action_url]);}
cbg_tracer.send_log('click_event',attrs,function(){});};if(document.addEventListener){document.addEventListener('click',click_event_log_handler,true);}else{document.addEvent('mouseup',click_event_log_handler);}
if(window.trace_log_name==undefined){return;}
if(typeOf(trace_log_name)==='string'){var key='trace_'+trace_log_name;cbg_tracer[key]&&cbg_tracer[key]();}else if(typeOf(trace_log_name)==='array'){for(var i=0;i<trace_log_name.length;i++){var key='trace_'+trace_log_name[i];cbg_tracer[key]&&cbg_tracer[key]();}}
cbg_tracer.trace_special_equip_lists();}
cbg_tracer.get_special=function(key){if(key=='Fingerprint'){return Cookie.read('fingerprint')||'-';}}
cbg_tracer.open_link=function(href){var referLink=document.createElement('a');referLink.href=href;document.body.appendChild(referLink);referLink.click();}
cbg_tracer.get_attrs=function(config){var attrs=[];for(var i=0;i<config.length;i++){if(!config[i]){continue;}
var name=config[i][0]
var conf=config[i][1];var type=conf.substr(0,1);var key=conf.substr(2);var v='';try{switch(type){case 'A':elem=config[i][2];prop=config[i][3];var isEmpty=function(v){return!v||v.indexOf('<!--')==0;}
if(key){v=elem.getElement(key).getProperty(prop);}else{v=elem.getProperty(prop);}
if(isEmpty(v)){prop=config[i][4];if(prop)
v=elem.getElement(key).getProperty(prop);if(isEmpty(v))
v='-';}
break;case 'L':elem=config[i][2];prop=config[i][3];v=elem.getElements(key).getProperty(prop);if(!v){v='-';}
v=JSON.encode(v);break;case 'F':v=cbg_tracer.get_special(key);break;case 'S':var res=$$(key).get('text');if(res.length>0){v=res.toString();}else{v='-';}
break;case 'V':v=trace_log_used_info[key];break;case 'E':try{v=eval(key);}catch(e){v='-';}
break;case 'C':v=key;break;default:v='ERR_TYPE('+conf+')';}
if(v==null||v==undefined){v='-';}}catch(e){v='ERROR';}
attrs.push([name,v]);}
return attrs;}
cbg_tracer.getUrlParam=function(name,url){var url=url||location.search;var result=new RegExp('[?&]'+name+'=([^&]*)').exec(url);return result?decodeURIComponent(result[1]):'';};cbg_tracer.send_log=function(log_name,attrs,callback){if(!window.Tracker){return;}
var img=new Image();var params={};(attrs||[]).each(function(list){params[list[0]]=list[1];});var external_origin=Cookie.read('_external_mark');if(external_origin){params.external_origin=external_origin;}
var from_external_id=cbg_tracer.getUrlParam('from_external_id');if(from_external_id){params.from_external_id=from_external_id;}
var sid=cbg_tracer.session.get();params.session_id=sid;params=Object.toQueryString(params);var wrapped_callback=null;var doing=false;if(callback){var wrapped_callback=function(){if(doing){return;}
doing=true;callback();}
img.onload=img.onerror=wrapped_callback;}
var src=Tracker.url+'/1.gif?v='+Math.random();src+='&log='+log_name+'&'+params;img.src=src;img.style.display='none';document.body.appendChild(img);if(wrapped_callback){setTimeout(wrapped_callback,500);}}
cbg_tracer.trace_select_role=function(){var old_login=window.login;window.login=function(){var roleid=LastRoleId;if(!roleid){roleid=$("select_roleid").value;}
var role=RoleList[roleid];var config=[['ver','C_1'],['ip','S_#client_ip'],['fingerprint','F_Fingerprint'],['urs','S_#user_urs'],['serverid','V_serverid'],['serversn','V_serversn'],['roleid','C_'+roleid],['nickname','C_'+role['nickname']],['icon','C_'+role['icon']],['race','C_'+role['racename']]];var attrs=cbg_tracer.get_attrs(config);cbg_tracer.send_log('select_role',attrs,function(){old_login();});};}
cbg_tracer.get_common_trace_info=function(){var is_login=Cookie.read('is_user_login')==1?true:false;var user_level='-';var roleid='-';var nickname='-';var icon='-';var urs='-';var school='-';if(is_login){var user_level=Cookie.read('login_user_level');var roleid=Cookie.read('login_user_roleid');var nickname=Cookie.read('login_user_nickname');var icon=Cookie.read('login_user_icon');var urs=Cookie.read('login_user_urs');var school=Cookie.read('login_user_school');}
var config=[['product','C_xyq'],['client_type','C_web'],['fingerprint','F_Fingerprint'],['urs','C_'+urs],['roleid','C_'+roleid],['nickname','C_'+nickname],['icon','C_'+icon],['grade','C_'+user_level],['school','C_'+school],['nav','S_.nav ul li.on'],['sub_nav','S_.subNav a.on'],['is_user_login','C_'+is_login],['useragent','C_'+navigator.userAgent]];if(window.LoginInfo){config.extend([['serverid','E_LoginInfo.serverid'],['serversn','E_LoginInfo.serversn']]);}else{config.extend([['serverid','E_ServerInfo.server_id'],['serversn','E_ServerInfo.server_sn']]);}
return config;}
cbg_tracer.get_equip_view_loc=function(el){var view_loc=el.getProperty('data_view_loc');if(!view_loc||view_loc.startWith('<!--')){view_loc=window.equip_refer_loc||'no_refer';if(view_loc.startWith('<!--')){view_loc='no_refer';}}
if(view_loc&&view_loc.indexOf('|')<0){var recommd_tag=el.getProperty('data_recommd_tag');if(recommd_tag&&!recommd_tag.startWith('<!--')){view_loc+='|{"tag": "'+recommd_tag+'"}';}}
return view_loc;};cbg_tracer.get_list_pos=function(e){if(e.getProperty('pos')){return e.getProperty('pos');}
var siblings=e.getParent().getChildren();var i=0;for(;i<siblings.length;i++){if(e==siblings[i]){break;}}
return i+1;}
cbg_tracer.get_search_conds=function(){var search_conds={};if(CommonVar.query_order){search_conds['query_order']=CommonVar.query_order;}
for(var k in QueryVar){if(!QueryVar[k]){continue;}
search_conds[k]=QueryVar[k];}
return search_conds;}
cbg_tracer.get_overall_search_conds=function(){var search_conds={};if(window.QueryArgs){for(var k in QueryArgs){if(!QueryArgs[k]){continue;}
search_conds[k]=QueryArgs[k];}
if(search_conds['act']){delete search_conds['act']}
if(search_conds['order_by']){search_conds['query_order']=search_conds['order_by'];delete search_conds['order_by'];}}
else{if(window.CurSearchValue==undefined){return;}
if(CurSearchValue.order_by&&CurSearchValue.order_by['key']!=null){search_conds['query_order']=CurSearchValue.order_by['key']+' '+CurSearchValue.order_by['sort'];}
if(CurSearchValue.arg){for(var k in CurSearchValue.arg){if(!CurSearchValue.arg[k]){continue;}
search_conds[k]=CurSearchValue.arg[k];}}
if($$('.pages>a.on')[0]){search_conds['page']=$$('.pages>a.on')[0].get('text');}}
return search_conds;}
cbg_tracer.trace_show_equip_detail=function(){var $root=$$('body');if($root.length>0){var keyInit='trace_solid_img_init';$root.each(function($r){if($r.get(keyInit)){return;}
$r.set(keyInit,1);$r.addEvent('click:relay(#soldList a.soldImg,#soldList a.jsStat,.jsStatEquips a.soldImg,.jsStatEquips a.jsStat)',function(e){var res=cbg_tracer.do_trace_show_equip_detail($(this).getParent('tr'));if(res===false){e.stop();}});$r.addEvent('mouseenter:relay(#soldList a.soldImg,.jsStatEquips a.soldImg)',function(){$(this).setProperty('mouse_over_begin',new Date());});$r.addEvent('mouseleave:relay(#soldList a.soldImg,.jsStatEquips a.soldImg)',function(){var begin=$(this).getProperty('mouse_over_begin');begin=new Date(begin);var end=new Date();var delta=end-begin;cbg_tracer.do_trace_show_tips_box($(this).getParent('tr'),delta);});});}else{setTimeout(cbg_tracer.trace_show_equip_detail,1000);}}
cbg_tracer.trace_special_equip_lists=function(){$$('#msg_detail .j_equip_icon a.soldImg').addEvents({mouseenter:function(){$(this).setProperty('mouse_over_begin',new Date());},mouseleave:function(){var begin=$(this).getProperty('mouse_over_begin');begin=new Date(begin);var end=new Date();var delta=end-begin;cbg_tracer.do_trace_show_tips_box($(this).getParent('.j_equip_icon'),delta);},click:function(){return cbg_tracer.do_trace_show_equip_detail($(this).getParent('.j_equip_icon'));}});var panels=$$('#latest_trades_list');if(panels.length==0)
return;panels.addEvent('click',function(e){var img=e.target;if(!img||img.tagName.toLowerCase()!='img')
return;return cbg_tracer.do_trace_show_equip_detail(img.getParent('li'));});$$('#latest_trades_list li').addEvents({mouseenter:function(){$(this).setProperty('mouse_over_begin',new Date());},mouseleave:function(){var begin=$(this).getProperty('mouse_over_begin');begin=new Date(begin);var end=new Date();var delta=end-begin;cbg_tracer.do_trace_show_tips_box(this,delta);}});$$('.j_link_order_detail_to_equip').addEvent('click',function(e){return cbg_tracer.do_trace_show_equip_detail_on_link(this,'order_in');});};cbg_tracer.get_common_info_for_equip_in_list=function(e){var config=cbg_tracer.get_common_trace_info();try{var value=e.getElement('td>textarea').value;var extra=JSON.decode(value);var search_conds=JSON.encode(cbg_tracer.get_search_conds());config.extend([['equip_serverid','E_ServerInfo.server_id']]);config.extend([['equip_serversn','E_ServerInfo.server_sn']]);}catch(exp){try{var extra=JSON.decode(e.getElement('a>textarea').value);var search_conds=JSON.encode(cbg_tracer.get_overall_search_conds());config.extend([['equip_serverid','A_a img',e,'data_equip_serverid','data_serverid']]);config.extend([['equip_serversn','A_a img',e,'data_equip_serversn','data_serversn']]);}catch(exp2){extra={};var search_conds='-';config.extend([['equip_serverid','A_a img',e,'data_equip_serverid','data_serverid']]);config.extend([['equip_serversn','A_a img',e,'data_equip_serversn','data_serversn']]);}}
if(!extra){extra={};}
var pos=cbg_tracer.get_list_pos(e);var view_loc=cbg_tracer.get_equip_view_loc(e.getElement('a img'));var highlightArr=[];if(extra.highlight){highlightArr=['highlight','C_'+extra.highlight];}else{highlightArr=['highlight','A_a img',e,'data_highlights'];}
var dynamicTagsArr=[];if(extra.dynamic_tags){dynamicTagsArr=['dynamic_tags','C_'+extra.dynamic_tags];}else{dynamicTagsArr=['dynamic_tags','A_a img',e,'data_dynamic_tags'];}
config.extend([['ver','C_1'],['view_loc','C_'+view_loc],['kind','S_#kind_tree_panel ul .on:not(.off)'],['search_conds','C_'+search_conds],['ordersn','A_a img',e,'data_ordersn'],['game_ordersn','A_a img',e,'data_ordersn'],['equip_type','A_a img',e,'data_equip_type'],['equip_level','A_a img',e,'data_equip_level'],['selling_time','A_a img',e,'data_selling_time','data_equip_selling_time'],['create_time','A_a img',e,'data_equip_create_time','data_create_time'],['kindid','A_a img',e,'data_kindid'],['price','A_a img',e,'data_equip_price','data_price'],highlightArr,dynamicTagsArr,['status','A_a img',e,'data_equip_status','data_status'],['pos','C_'+pos]]);if(!extra.seller_roleid){config.extend([['seller_roleid','A_a img',e,'data_seller_roleid','data_owner_roleid']]);}else{config.extend([['seller_roleid','C_'+(extra.seller_roleid?extra.seller_roleid:'-')]]);}
var attrs=cbg_tracer.get_attrs(config);for(var i=0;i<attrs.length;i++){var key=attrs[i][0];var val=attrs[i][1];if(key!=='selling_time'&&key!=='create_time'){continue;}else if(val.contains(':')||val==='-'){continue;}
val=parseInt(val)*1000;d=new Date(val);attrs[i][1]=d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate()+' '+d.getHours()+':'+d.getMinutes()+':'+d.getSeconds()}
return attrs;}
cbg_tracer.do_trace_show_equip_detail_on_link=function(e,view_loc){var config=cbg_tracer.get_common_trace_info();config.extend([['equip_serverid','E_ServerInfo.server_id'],['equip_serversn','E_ServerInfo.server_sn'],['ver','C_1'],['view_loc','C_'+view_loc],['kind','C_-'],['search_conds','C_-'],['ordersn','A',e,'data_ordersn'],['equip_type','A',e,'data_equip_type'],['equip_level','A',e,'data_equip_level'],['selling_time','A',e,'data_selling_time','data_equip_selling_time'],['create_time','A',e,'data_equip_create_time','data_create_time'],['kindid','A',e,'data_kindid'],['price','A',e,'data_equip_price','data_price'],['highlight','C_-'],['status','A',e,'data_equip_status','data_status'],['pos','C_-'],['seller_roleid','A',e,'data_seller_roleid','data_owner_roleid'],['storage_type','A',e,'data_storage_type']]);var attrs=cbg_tracer.get_attrs(config);for(var i=0;i<attrs.length;i++){var key=attrs[i][0];var val=attrs[i][1];if(key!=='selling_time'&&key!=='create_time'){continue;}else if(val.contains(':')||val==='-'){continue;}
val=parseInt(val)*1000;d=new Date(val);attrs[i][1]=d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate()+' '+d.getHours()+':'+d.getMinutes()+':'+d.getSeconds()}
var log_name='show_equip_detail';if(e.getProperty('target')!='_blank'){cbg_tracer.send_log(log_name,attrs,function(){cbg_tracer.open_link(e.href);});return false;}else{cbg_tracer.send_log(log_name,attrs);return true;}};cbg_tracer.do_trace_show_equip_detail=function(e,options){var a_elem=e.getElement('a.soldImg')||e.getElement('a img').getParent('a');options=Object.merge({sendLog:true},options||{});var attrs=cbg_tracer.get_common_info_for_equip_in_list(e);if(!attrs){return;}
var log_name='show_equip_detail';var recommd_tag=e.getElement('a img').getProperty('data_recommd_tag');var migrate_flag=['true','True','1'].contains(e.getElement('a img').getProperty('data_time_lock'));var migrate_days=['true','True','1'].contains(e.getElement('a img').getProperty('data_time_lock_days'));attrs.push(['migrate_flag',Number(migrate_flag)]);attrs.push(['migrate_days',Number(migrate_days)]);if(recommd_tag&&!recommd_tag.startWith('<!--')){attrs.push(['tag',recommd_tag]);}
var reco_request_id=e.getElement('a img').get('data_reco_request_id');if(reco_request_id){attrs.push(['reco_request_id',reco_request_id]);}
var sell_by_apart_type=e.getElement('a img').get('data_sell_by_apart_type');if(sell_by_apart_type){var whole_game_ordersn=e.getElement('a img').get('data_whole_game_ordersn');attrs.push(['sell_by_apart_type',sell_by_apart_type]);attrs.push(['whole_game_ordersn',whole_game_ordersn]);}
var storage_type=e.getElement('a img').getProperty('data_storage_type');if(storage_type){attrs.push(['storage_type',storage_type]);}
if(!options.sendLog){return attrs;}
if(a_elem.getProperty('target')!='_blank'){cbg_tracer.send_log(log_name,attrs,function(){cbg_tracer.open_link(a_elem.href);});return false;}else{cbg_tracer.send_log(log_name,attrs);return true;}}
cbg_tracer.do_trace_show_tips_box=function(e,delta){var $img=e.getElement('a img');var storage_type=$img.getProperty('data_storage_type');if(delta<500||storage_type==StorageStype['money']){return;}
var attrs=cbg_tracer.get_common_info_for_equip_in_list(e);if(!attrs)return;attrs.push(['duration',delta]);if(storage_type){attrs.push(['storage_type',storage_type]);}
var log_name='show_tips_box';var recommd_tag=e.getElement('a img').getProperty('data_recommd_tag');if(recommd_tag&&!recommd_tag.startWith('<!--')){attrs.push(['tag',recommd_tag]);}
cbg_tracer.send_log(log_name,attrs);}
cbg_tracer.trace_pay_cross_server_order=function(){if(window.goto_pay_orders){var old_goto_pay_orders=window.goto_pay_orders;window.goto_pay_orders=function(){var config=cbg_tracer.get_common_trace_info();var e=$$('#soldList')[0];config.extend([['ver','C_1'],['type','C_'+trace_log_name],['price','A_a img',e,'data_equip_price'],['equip_serverid','E_equip_info.serverid'],['equipid','A_a img',e,'data_equipid']]);var attrs=cbg_tracer.get_attrs(config);cbg_tracer.send_log('goto_epay',attrs);return old_goto_pay_orders.apply(this,arguments);}}}
cbg_tracer.trace_merge_pay=function(){if(window.do_pay){var old_do_pay=window.do_pay;window.do_pay=function(){var config=cbg_tracer.get_common_trace_info();var e=$$('#soldList')[0];config.extend([['ver','C_1'],['type','C_'+trace_log_name],['price','L_a img',e,'data_equip_price'],['equip_serverid','E_ServerInfo.server_id'],['equipid','L_a img',e,'data_equipid']]);var attrs=cbg_tracer.get_attrs(config);cbg_tracer.send_log('goto_epay',attrs);return old_do_pay.apply(this,arguments);}}}
cbg_tracer.trace_pay_in_order_list=function(){if(window.go_pay){var old_go_pay=window.go_pay;window.go_pay=function(orderid){var config=cbg_tracer.get_common_trace_info();var e=$$('#soldList')[0];config.extend([['ver','C_1'],['type','C_'+trace_log_name],['price','A_#equip_img_'+orderid,e,'data_equip_price'],['equip_serverid','E_ServerInfo.server_id'],['equipid','A_#equip_img_'+orderid,e,'data_realequipid']]);var attrs=cbg_tracer.get_attrs(config);cbg_tracer.send_log('goto_epay',attrs);return old_go_pay.apply(this,arguments);}}}
cbg_tracer.trace_pay_in_detail_page=function(){if(window.go_pay){var old_go_pay=window.go_pay;window.go_pay=function(){var config=cbg_tracer.get_common_trace_info();var e=$$('#soldList')[0];config.extend([['ver','C_1'],['type','C_'+trace_log_name],['price','V_price'],['equip_serverid','E_ServerInfo.server_id'],['equipid','E_document.equip_info.equipid.value']]);var attrs=cbg_tracer.get_attrs(config);cbg_tracer.send_log('goto_epay',attrs);return old_go_pay.apply(this,arguments);}}}
cbg_tracer.get_equip_detail_config=function(){function get_view_loc_tag(view_loc){function is_object_str(str){var res=true;try{JSON.parse(str);}catch(e){res=false;}
return res;}
var result='-';if(view_loc){var split_array=view_loc.split('|');if(split_array[1]&&is_object_str(split_array[1])){var tempTag=JSON.parse(split_array[1]).tag;result=tempTag===undefined?'-':tempTag;}}
return result;}
var referrer=document.referrer;if(/\/login\.py.*act=do_anon_auth/.test(referrer)){referrer='';}
var view_loc='link_external';var tag='-';if(window.equip_refer_loc){view_loc=equip_refer_loc;tag=get_view_loc_tag(equip_refer_loc);}else if(referrer===''){window.equip_refer_loc=view_loc='link_external';}
var config=cbg_tracer.get_common_trace_info();config.extend([['highlight','C_'+(equip.highlights?JSON.encode(equip.highlights):'-')],['ver','C_1'],['view_loc','C_'+view_loc],['ordersn','E_equip.game_ordersn'],['game_ordersn','E_equip.game_ordersn'],['equip_type','E_equip.equip_type'],['selling_time','E_equip.selling_time'],['create_time','E_equip.create_time'],['kindid','E_equip.kindid'],['seller_roleid','E_equip.owner_roleid'],['price','E_equip.price'],['equip_serversn','E_equip.serversn'],['equip_level','E_equip.equip_level'],['status','E_equip.status'],['storage_type','E_equip.storage_type'],['tag','C_'+tag]]);var reco_request_id=cbg_tracer.getUrlParam('reco_request_id');if(reco_request_id){config.extend([['reco_request_id','C_'+reco_request_id]]);}
return cbg_tracer.get_attrs(config);}
cbg_tracer.trace_in_equip_detail_page=function(options){options=Object.merge({sendLog:true},options||{});var attrs=cbg_tracer.get_equip_detail_config();if(!options.sendLog){return attrs;}
var prefix=document.location.protocol+'//'+document.location.host;var referrer=document.referrer;if(location.search.match(/equip_refer=56|_web_log=1/)){}else if(/\/login\.py.*act=do_anon_auth/.test(referrer)){referrer='';}else if(referrer.startWith(prefix)){return;}
cbg_tracer.send_log('show_equip_detail',attrs);}
cbg_tracer.trace_recommd_in_equip_detail_page=function($root){if($root){if($root.getAttribute('trace_init')){return;}
$list=$root.getElements('.guessList a');}else{$root=$$('.guess.goodsInfo');if($root.length<=0){return;}
$root.each(function($r){cbg_tracer.trace_recommd_in_equip_detail_page($r);});return;}
if($list.length>0){$root.setAttribute('trace_init',1);$list.addEvent('click',function(){cbg_tracer.do_trace_recommd_in_equip_detail_page($(this).getParent('li'));return true;});$list.addEvent('mouseover',function(){$(this).setProperty('mouse_over_begin',new Date());});$list.addEvent('mouseout',function(){var begin=$(this).getProperty('mouse_over_begin');if(!begin){return;}
begin=new Date(begin);var end=new Date();var delta=end-begin;cbg_tracer.do_trace_show_tips_box_in_equip_detail_page($(this).getParent('li'),delta);});var data={};if(window.equip){data.ref_ordersn=window.equip.game_ordersn||'-';data.ref_equip_serversn=window.equip.serversn||'-';}
cbg_tracer.listen_equips_exposure($root,'equipDetailRecommand',{data:data});}else{var times=+($root.getAttribute('times_retry')||'0');if(times<5){$root.setAttribute('times_retry',times+1);setTimeout(function(){cbg_tracer.trace_recommd_in_equip_detail_page($root);},3000);}}}
cbg_tracer.do_trace_recommd_in_equip_detail_page=function(e){var config=cbg_tracer.get_common_trace_info();var view_loc=cbg_tracer.get_equip_view_loc(e.getElement('a img'));config.extend([['highlight','A_a img',e,'data_highlights'],['ver','C_1'],['kind','S_#kind_tree_panel ul .on:not(.off)'],['tag','A_a img',e,'data_recommd_tag'],['type','C_from_detail_page'],['view_loc','C_'+view_loc],['ordersn','A_a img',e,'data_ordersn'],['equip_type','A_a img',e,'data_equip_type'],['equip_level','A_a img',e,'data_equip_level'],['selling_time','A_a img',e,'data_selling_time','data_equip_selling_time'],['create_time','A_a img',e,'data_create_time'],['kindid','A_a img',e,'data_kindid'],['seller_roleid','A_a img',e,'data_owner_roleid'],['price','A_a img',e,'data_price'],['equip_serversn','A_a img',e,'data_serversn','data_equip_serversn'],['status','A_a img',e,'data_status'],['ref_equip_serversn','E_equip.serversn'],['ref_ordersn','E_equip.game_ordersn'],['pos','C_'+cbg_tracer.get_list_pos(e)],['storage_type','A_a img',e,'data_storage_type'],['reco_request_id','A_a img',e,'data_reco_request_id']]);var attrs=cbg_tracer.get_attrs(config);cbg_tracer.send_log('show_equip_detail',attrs);}
cbg_tracer.do_trace_show_tips_box_in_equip_detail_page=function(e,delta){var storage_type=e.getElement('a img').getProperty('data_storage_type');if(delta<500||storage_type==StorageStype['money']||storage_type==StorageStype['role']){return;}
var config=cbg_tracer.get_common_trace_info();var view_loc=cbg_tracer.get_equip_view_loc(e.getElement('a img'));config.extend([['highlight','A_a img',e,'data_highlights'],['ver','C_1'],['kind','S_#kind_tree_panel ul .on:not(.off)'],['tag','A_a img',e,'data_recommd_tag'],['type','C_from_detail_page'],['view_loc','C_'+view_loc],['ordersn','A_a img',e,'data_ordersn'],['equip_type','A_a img',e,'data_equip_type'],['equip_level','A_a img',e,'data_equip_level'],['selling_time','A_a img',e,'data_selling_time','data_equip_selling_time'],['create_time','A_a img',e,'data_create_time'],['kindid','A_a img',e,'data_kindid'],['seller_roleid','A_a img',e,'data_owner_roleid'],['price','A_a img',e,'data_price'],['equip_serversn','A_a img',e,'data_serversn','data_equip_serversn'],['status','A_a img',e,'data_status'],['duration','C_'+delta],['ref_equip_serversn','E_equip.serversn'],['ref_ordersn','E_equip.game_ordersn'],['pos','C_'+cbg_tracer.get_list_pos(e)],['storage_type','A_a img',e,'data_storage_type']]);var attrs=cbg_tracer.get_attrs(config);cbg_tracer.send_log('show_tips_box',attrs);}
cbg_tracer._load_exposure_logger=function(){return new Promise(function(resolve,reject){Asset.javascript(ResUrlVer+'/js/log/exposure.js',{defer:1,async:1,onLoad:function(){var map={};resolve(function getInstance(id,opts){if(!map[id]){map[id]=new LogExposure(Object.merge({attr:'log-exposure',data:{}},opts||{}));}
var logger=map[id];return{logger:logger,clear:function(){logger.clear();},watch:function(el,options){var key='__exposure_unwatch';el[key]&&el[key]();el[key]=logger.watch(el,Object.merge({unwatchWhenAllExposure:true,onUnwatch:function(){delete el[key];}},options||{}));}};});}});});}
cbg_tracer.listen_equips_exposure=function(selector,instanceId,options){selector=selector||'[log-exposure-container]';instanceId=instanceId||'equipsList';this._load_exposure_logger().then(function(getInstance){var instance=getInstance(instanceId,Object.merge({data:{log:'equip_exposure'}},options||{}));instance.clear();$$(selector).forEach(function(el){instance.watch(el,{beforeLog:function(data,tr){var attrs=cbg_tracer.do_trace_show_equip_detail(tr,{sendLog:false});if(!attrs||attrs.length<=0){return false;}
var params={};(attrs||[]).forEach(function(arr){params[arr[0]]=arr[1];});return Object.merge(params,data);}});});});}
window.addEvent('domready',cbg_tracer.init);